### ISSUE TITLE
Incorrect city assignment for certain street segments

### ISSUE THREAD

**Issue by JonathanMontane** [openstreetmap/Nominatim#1018]
### Issue
In some cases, the segments of a street are assigned to the wrong city.

#### Expectation
In Andorra, `Avinguda Carlemany` is in `Les Escaldes`, and becomes Avinguda Meritxell when in `Andorra La Vella`. We therefore expect that all of the street segments of Avinguda Carlemany are in Les Escaldes.

#### Reality
Instead the segment of Avinguda Carlemany closest to Andorra la Vella is said to belong to Andorra La Vella.

#### Links
Link to details: https://nominatim.openstreetmap.org/details.php?place_id=77454508
OSM Object: https://www.openstreetmap.org/way/30922493

#### Expectation
In Andorra, `Avinguda del Consell de la Terra` is in `Les Escaldes`.

#### Reality
It is instead declared as belonging to `Andorra la Vella`.

#### Links
Link to details: https://nominatim.openstreetmap.org/details.php?place_id=76617062
OSM Object: https://www.openstreetmap.org/way/24914989#map=18/42.50930/1.53637

### Possible reasons
The OSM Object for Andorra la Vella seems correct ([link](https://www.openstreetmap.org/relation/2804753#map=17/42.50765/1.53299)) and is a relation.

However, the OSM Object for Les Escaldes is a node ([link](https://www.openstreetmap.org/node/64954589)), and I guess that this is maybe what is causing issues. 

It is also possible that these street segments are very slightly clipping into the administrative boundary of Andorra la Vella.

### Fallback version
This issue was caused by changes introduced after version 2.4.0 as it was not present in Nominatim 2.4.0, but I don't know which one exactly.

**Comment by LNFWebsite** [comment]
Same issue here...

**Comment by lonvia** [comment]
Is there any boundary relation for Les Escaldes? Then this probably needs fixing. If there is none, you should add one. The streets are touching the boundary of Andorra la Vella and as long as there is a boundary relation for only one of the two suburbs, it is close to impossible to fix that in Nominatim without severely breaking other addresses.

Closing as being an OSM data issue.

**Comment by LNFWebsite** [comment]
This isn't only an issue with that specific address. It occurs in other locations as well.

If it is truly an OSM data issue, you should alert them of this issue with their data. The accuracy of address resolution can make or break the operation of OSM for many intents and purposes.

**Comment by lonvia** [comment]
@LNFWebsite It isn't as simple as that. 'Incorrect city assignment' is a very broad description for a symptom that can have a lot of different causes. This particular one had a data issue at its root. Others are actually due to bugs or missing features in Nominatim. There are dozens of tickets open in this issue tracker that address the different known short-comings. Most of them are time-intensive to address, so it will take a while to get to them. In the meantime you can help out yourself with addressing the issues where they are problems with the underlying OSM data. There really is no 'alerting the authorities' here. OSM is a community-driven database and stands and falls with people being willing to help out.

**Comment by LNFWebsite** [comment]
Thanks for the reply. I see what you mean...

I thought that the OSM data issue you spoke of had to do with the handling of the data rather than the data itself.
