### ISSUE TITLE
Brighton Dr. numbering all wrong

### ISSUE THREAD

**Issue by cf8geek** [openstreetmap/Nominatim#1026]
Brighton Dr. in Waukee, IA (USA) has 800 showing up in about 1/3 up the street, immediately below that is listed as 898 Brighton Dr., continuing to lower numbers as the street goes South. At the top of the segment, the numbers restart around 822 and continue to decrease until 800.

This is wrong for several reasons:
1. there aren't that many house numbers
2. all the numbers listed on the West of the segment are even, and on the East they're odd; in reality, the numbers just go sequentially per side

See also:
41.60984, -93.8653

I cannot figure out how to edit this on OpenStreetMap or I'd fix it myself. Also, it looks like people haven't received much help when asking about this in the past. https://help.openstreetmap.org/questions/11222/correcting-location-of-an-address

**Comment by mtmail** [comment]
For the USA Nominatim used two data sources: OpenStreetMap and secondary US Census (so called TIGER) data. Now it's confusing that you see Nominatim results from TIGER but can't see the same on the map. TIGER can't be hand-edited, well at least not online.

Can you add house numbers to the street? They will overwrite the TIGER data. Just click the "Edit" tab (similar to wikipedia) place a Point on the map, select "Address" and house number and street. City/State/Postcode are optional. 

![image](https://user-images.githubusercontent.com/3727288/39522739-7686a274-4e13-11e8-915c-6165a013e58a.png)

If you just add the first and last house of each street side (4 addresses), then I could add an interpolation line https://wiki.openstreetmap.org/wiki/JOSM/Plugins/AddrInterpolation with a different editor. That's a bit more advanced. For long streets, or many streets it just saves time but is a little less accurate as it assumes an even distribution of house numbers.

I can't add house numbers myself because I don't have local knowledge. Copying from other maps is not allowed, and as you say the TIGER data is inaccurate here.

**Comment by lonvia** [comment]
This is a bug tracker for the Nominatim software, not for OSM data issues. So I'm sorry to say that this is also the wrong place to ask for help in this particular matter. If you don't want to fix the data in OpenStreetMap yourself, I recommend adding a note at the place and hopefully a friendly local mapper will help you out. For more information see https://www.openstreetmap.org/fixthemap .
