### ISSUE TITLE
I am getting different output from official osm nominatim, and i do not know why.

### ISSUE THREAD

**Issue by yoshi314** [openstreetmap/Nominatim#1047]
I imported data for several countries by merging them into one o5m file and loading via --osmosis-import-all and the results are a bit off.

First of all, i have no such pretty print as presented here : 

https://nominatim.openstreetmap.org/search.php?format=jsonv2&addressdetails=1&namedetails=1&extratags=1&city=STOCKHOLM&postalcode=111+64&debug=1

On my local instance, what i get is the output presented here, which looks like html mixed with php debug output (despite having debug disabled in nominatim configuration), and is missing several sections that official interface provides.

https://gist.github.com/yoshi314/d1ad070051f7147b56c42b7e1af66213

I have none of the "Debug output for Geocode::lookup" or other query preprocessing sections. I am using Nominatim 3.1.0

**Comment by lonvia** [comment]
osm.org always runs something close to latest master. You are looking at features that have been introduced after 3.1.0 was released.

You can't compare data exactly either because the osm.org instance has been running on updates for a long time and contains a full planet. Using extracts and a new import tends to produce slightly different results.

**Comment by yoshi314** [comment]
I tried git release, no change in the output. 

Also, the official service has additional handling for malformed postal codes, which is the thing that interests me the most.
