### ISSUE TITLE
OSM data updating issue

### ISSUE THREAD

**Issue by Rajavelu** [openstreetmap/Nominatim#1051]
hi

I met the following error while updating osm data using nominatim & osmosis. (Working fine till 2 weeks before).
Kindly help someone to me to solve this issue.

**State.txt**
#Wed May 09 00:01:16 PDT 2018
sequenceNumber=49457
timestamp=2018-05-05T00\:00\:00Z

**configuration.txt** 
baseUrl=http://planet.openstreetmap.org/replication/day
maxInterval = 86400

**local.php**
@define('CONST_Replication_Url', 'https://planet.openstreetmap.org/replication/day');
@define('CONST_Replication_MaxInterval', '3600');     
@define('CONST_Replication_Update_Interval', '86400');  

I have tried _hour_ instead of _day_  but still met same error.

**Error details:**
org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-replication-interval failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: The replication state doesn't contain a timestamp property.
      
**Tried as https url in configuration.txt, but met connection timeout err as follows:**
org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-replication-interval failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to read the state from the server.
    at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:116)

**Comment by Rajavelu** [comment]
Diff file can be downloadable from https://planet.openstreetmap.org/replication/day/000/002/
& can be updated directly as _update.php --import-osmosis-all --no-npi_
But is it the right way to do ?

**Comment by mtmail** [comment]
In `configuration.txt` change `http://` to `https://`. Osmosis has trouble following redirects (https://trac.openstreetmap.org/ticket/5483)

**Comment by Rajavelu** [comment]
@mtmail Thanks for your answer. But still met connection timeout error when given https.

org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-replication-interval failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to read the state from the server.
at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:116)

**Comment by mtmail** [comment]
You posted
```
wget "http://osm.personalwerk.de/replicate-sequences/?"$lastNodeDate"&stream=hour" -O $WORKOSM_DIR/state.txt
```
as part of your custom script.

When I try
```
wget 'http://osm.personalwerk.de/replicate-sequences/?2015-10-24T12:58:56Z&stream=hour'
```
I get redirected to https. And that fails with error `To connect to osm.personalwerk.de insecurely, use --no-check-certificate'` Adding that parameters returns an `403 forbidden` error.

I would say since browsers proper follow the redirect(s) to the mazdermind.de server, replace the wget line in the custom script to
```
wget "https://replicate-sequences.osm.mazdermind.de/?"$lastNodeDate"&stream=hour" -O $WORKOSM_DIR/state.txt
```
It probably started failing when the osm.personalwerk.de server started enforcing (and redirecting to) https.

> I have tried hour instead of day but still met same error.

Remember to switch back to day! Nominatim wrote the last sequence id of daily updates into the database. With hourly it starts thinks there were no previous updates and goes back to 2015, overwriting existing data with older data.
