### ISSUE TITLE
Street address taken from neighbouring street, not address tag

### ISSUE THREAD

**Issue by TZornG** [openstreetmap/Nominatim#1056]
In the [German Forum](https://forum.openstreetmap.org/viewtopic.php?pid=702642#p702642) someone raised an issue not being able to find a certain building in Italy with Nominatim. The building in question is tagged with 

building = yes
addr:city = Trichiana
addr:postcode=32028
addr:street=Via Cavassico superiore
addr:housenumber=19

Yet [in Nominatim the street address of the building is Via Frazione Cavassico](https://nominatim.openstreetmap.org/details.php?place_id=237509774). Nominatim should take the street address information from the tag instead. Searching for something like "Via Cavassico superiore 19, 32028 Trichiana" only returns the street but not the building.

**Comment by mtmail** [comment]
Below just a small part of the debug output for https://nominatim.openstreetmap.org/search.php?q=Via+Cavassico+superiore+19%2C+Trichiana&polygon_geojson=1&viewbox=&debug=1

Nominatim interpreted the 19 as an Italian postcode because there was a hotel with that address (https://www.openstreetmap.org/edit?node=4227191664). That exhausted the number of search candidates it prepared. I fixed the hotel's postcode (https://www.openstreetmap.org/changeset/59694880) and it need a day for Nominatim to recalculate postcode boundaries.

![image](https://user-images.githubusercontent.com/3727288/41193974-be6732ec-6c14-11e8-8851-5d1d1ca3015e.png)

Let's see if that also makes the query without commas work https://nominatim.openstreetmap.org/search.php?q=Via+Cavassico+superiore+19+32028+Trichiana&polygon_geojson=1 or if we find a secondary issue.

We have plans to better deal with invalid postcodes and some work was done in May as first step.

**Comment by TZornG** [comment]
Not sure your finding is related. In my opinion the culprit is that the Nominatim place_id 237509774 associates the building in question with the wrong street. It should be Via Cavassico superiore as in the addr:street tag. Yet Nominatim seems to place the building on Via Frazione Cavassico, which touches the property on another side: https://nominatim.openstreetmap.org/details.php?place_id=237509774

**Comment by lonvia** [comment]
Nominatim does look into the `addr:street` tag but it is already quite happy with the partial match of 'Cavassico' in 'Via Frazione Cavassico'. That surely is a bug.

**Comment by lonvia** [comment]
Turns out the issue was more complicated. Nominatim sometimes ends up with duplicates of search tokens and that was not handled correctly when looking up the street from the `addr:street` tag. Fix is now deployed and I've refreshed the building in question.
