### ISSUE TITLE
Incorrect town for search result

### ISSUE THREAD

**Issue by guyiac** [openstreetmap/Nominatim#1057]
When I run a search for 41.31779, -72.7323, it shows as Wilderwood Drive in the town of North Branford. The town should be Guilford, and though it is within a mile of North Branford, the location is most definitely Guilford.   https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=17220727&class=highway

**Comment by mtmail** [comment]
That's due to missing data. While OpenStreetMap data contains Guilford as node (https://www.openstreetmap.org/node/158912354), there is no boundaries yet.

Below a map of Connecticut where circles are nodes. I created it on http://overpass-turbo.eu/ using the wizard feature looking for `admin_level=8` (8 is towns).

![image](https://user-images.githubusercontent.com/3727288/41193327-ca7f8084-6c0a-11e8-8419-0ed5bbe44b72.png)

I found the "Connecticut and Vicinity Town Boundary Polygon" shapefile data set http://www.ct.gov/deep/cwp/view.asp?a=2698&q=322898&deepNav_GID=1707%20 which according to their FAQ is public domain (thus license compatibly with OpenStreetMap for import) http://www.cteco.uconn.edu/metadata/dep/document/ct_vicinityindex_town_line_FGDC_FAQ.htm#getacopy.0

![image](https://user-images.githubusercontent.com/3727288/41193456-29c36fdc-6c0c-11e8-9eab-35e4293cbbef.png)

The OpenStreetMap community doesn't have a central team or issue tracker for missing data. Your best option is emailing https://lists.openstreetmap.org/listinfo/talk-us to see if a local mapper is interested/motivated/has free time to add those boundaries. It's probably a full day of work plus coordinating because import needs to be announced (risk of duplicating data, more than one person should review the license terms etc).

Searching in the neighboring state Rhode Island it looks like https://www.openstreetmap.org/user/azsr added all the town boundaries there. He/she might be a good contact or available to teach how the imports were done.

**Comment by guyiac** [comment]
Thanks for the response. With the change in Google Maps, I am looking for alternatives, so I am just learning how the Open Street Maps ecosystem works.

Guy Iaccarino
Greenleaf Advancement
Phone: 203-624-4636, ext. 111
Post: PO Box 617, Guilford CT 06437
Email <mailto:guyiac@greenleafadvancement.com> | Website <http://greenleafadvancement.com/> | LinkedIn <http://www.linkedin.com/in/guyiac> | Twitter <http://twitter.com/greenleaf_adv>




On Jun 9, 2018, at 11:51 AM, mtmail <notifications@github.com> wrote:

That's due to missing data. While OpenStreetMap data contains Guilford as node (https://www.openstreetmap.org/node/158912354 <https://www.openstreetmap.org/node/158912354>), there is no boundaries yet.

Below a map of Connecticut where circles are nodes. I created it on http://overpass-turbo.eu/ <http://overpass-turbo.eu/> using the wizard feature looking for admin_level=8 (8 is towns).

 <https://user-images.githubusercontent.com/3727288/41193327-ca7f8084-6c0a-11e8-8419-0ed5bbe44b72.png>
I found the "Connecticut and Vicinity Town Boundary Polygon" shapefile data set http://www.ct.gov/deep/cwp/view.asp?a=2698&q=322898&deepNav_GID=1707%20 <http://www.ct.gov/deep/cwp/view.asp?a=2698&q=322898&deepNav_GID=1707%20> which according to their FAQ is public domain (thus license compatibly with OpenStreetMap for import) http://www.cteco.uconn.edu/metadata/dep/document/ct_vicinityindex_town_line_FGDC_FAQ.htm#getacopy.0 <http://www.cteco.uconn.edu/metadata/dep/document/ct_vicinityindex_town_line_FGDC_FAQ.htm#getacopy.0>
 <https://user-images.githubusercontent.com/3727288/41193456-29c36fdc-6c0c-11e8-9eab-35e4293cbbef.png>
The OpenStreetMap community doesn't have a central team or issue tracker for missing data. Your best option is emailing https://lists.openstreetmap.org/listinfo/talk-us <https://lists.openstreetmap.org/listinfo/talk-us> to see if a local mapper is interested/motivated/has free time to add those boundaries. It's probably a full day of work plus coordinating because import needs to be announced (risk of duplicating data, more than one person should review the license terms etc).

Searching in the neighboring state Rhode Island it looks like https://www.openstreetmap.org/user/azsr <https://www.openstreetmap.org/user/azsr> added all the town boundaries there. He/she might be a good contact or available to teach how the imports were done.
