### ISSUE TITLE
No results in a bounded viewbox

### ISSUE THREAD

**Issue by arbitrary-dev** [openstreetmap/Nominatim#1065]
https://nominatim.openstreetmap.org/search?q=recycling&viewbox=24.14651,56.96626,24.14963,56.96480&bounded=1

But in OSM there are at least 3 recycling points:
https://www.openstreetmap.org/#map=19/56.96553/24.14785

**Comment by arbitrary-dev** [comment]
Okay, if I use [special phrases](https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/EN) like "Recycling Points", it still shows only 1 such point:
https://nominatim.openstreetmap.org/search?q=recycling+points&viewbox=24.14651,56.96626,24.14963,56.96480&bounded=1

Why is it so?

**Comment by mtmail** [comment]
All three are initially found, but then seen as duplicate because they're close together and have the same name (in this case: no name). Add `dedupe=0` to get all three.

https://nominatim.openstreetmap.org/search?q=recycling+points&viewbox=24.14651,56.96626,24.14963,56.96480&bounded=1&dedupe=0

The Overpass API (https://wiki.openstreetmap.org/wiki/Overpass_API) might also be helpful, if not more powerful, for such queries. http://overpass-turbo.eu/

![image](https://user-images.githubusercontent.com/3727288/41502012-194a5a22-71b0-11e8-9ce6-9ce20bd27b2e.png)

**Comment by arbitrary-dev** [comment]
Great, thanks!
