### ISSUE TITLE
Response of search on "8580 CH" incomplete

### ISSUE THREAD

**Issue by rschi** [openstreetmap/Nominatim#1130]
If I search "8580 CH" I get only Hefenhofen as result:
https://www.openstreetmap.org/relation/1684527

But Amriswil (next to Hefenhofen) has also the Postalcode "8580"

The search "8580 CH" should deliver four results:
- Amriswil
- Hefenhofen
- Dozwil
- Sommeri

Check also on http://www.postleitzahlen.ch

**Comment by gormo-osm** [comment]
It's a data problem. postal_code is not tagged on the other admin relations, only on Hefenhofen.
See https://overpass-turbo.eu/s/ATv , all admin relations in the region tagged with postal_code.

**Comment by lonvia** [comment]
If you search for a post code in Nominatim, you get a postcode with an address returned. That address has by design always only one village. It is not possible to change that.

There is no way to enter a postcode and get a list of places that have that postcode. Due to the erratic nature of postcodes it is also unlikely that such a feature would ever be implemented.
