### ISSUE TITLE
discarding "named after" name part in Polish

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/Nominatim#1135]
"im." in Polish is short of "imienia" and means "named after".

Users are likely to not use full official name and some objects are tagged only with it.

For example searching "Szkoła Podstawowa nr 93, Kraków" will fail - https://www.openstreetmap.org/search?query=Szko%C5%82a+Podstawowa+nr+93,%20Krak%C3%B3w#map=19/50.07372/19.90089 despite that https://www.openstreetmap.org/way/230183651#map=19/50.07372/19.90089 with name "Szkoła Podstawowa nr 93 im. Lucjana Rydla" exists.

I would expect that searching both "Szkoła Podstawowa nr 93 im. Lucjana Rydla" and "Szkoła Podstawowa nr 93" will find this object.

**Comment by lonvia** [comment]
https://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations is a more appropriate place to collect abbreviations like that. Add a note that it should be splitting the name instead of being extended.

That said these kind of name tags that collect multiple name tags are really a pain to process. I strongly suggest to add name tags for the parts to give computers the appropriate hint where to split them.

**Comment by matkoniecz** [comment]
This problem is not covered by https://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations

This is case of discarding part of name so

`Szkoła Podstawowa nr 93 im. Lucjana Rydla` and `Szkoła Podstawowa nr 93` would be considered equivalent.
