### ISSUE TITLE
An error during planet installation

### ISSUE THREAD

**Issue by llomgui** [openstreetmap/Nominatim#1168]
Hey,

I was doing a planet installation and 24 hours later, I got an error:

> ╰─➤  tail -f setup.log
  Done 44742726 in 44159 @ 1013.218750 per second - Rank 26 ETA (seconds): 24107.109375
  Done 44743218 in 44160 @ 1013.206970 per second - Rank 26 ETA (seconds): 24106.904297
  Done 44744024 in 44161 @ 1013.202209 per second - Rank 26 ETA (seconds): 24106.222656
index_placex: UPDATE failed: ERROR:  buffer 82340 is not owned by resource owner Portal
CONTEXT:  SQL statement "INSERT INTO search_name_88 (place_id, search_rank, address_rank, name_vector, centroid)
        values (in_place_id, in_rank_search, in_rank_address, in_name_vector, in_geometry)"
PL/pgSQL function insertsearchname(integer,bigint,character varying,integer[],integer[],integer,integer,double precision,geometry,geometry) line 247 at SQL statement
PL/pgSQL function placex_update() line 681 at assignment
ERROR: error status 1 running nominatim!
error status 1 running nominatim!

Can you tell me what I missed?

**Comment by mtmail** [comment]
I've seen the "not owned by resource owner" before. I'm afraid it turned out to be a hardware issue, likely CPU. Eventually, after 10 restarts of the import command it finished. I did RAM and file system checks and they were fine. Nominatim version and Postgresql version made no difference, smaller imports always ran fine, only the heavy CPU load of a full planet caused the issues after many hours. Postgresql forum posts (internet search) pointed to issues in multithreading (or hyperthreading with my CPU).

You can try running the import with less threads and check if you have all microcode upgrades for the CPU applied. If it's easy in your infrastructure (cloud vs shared hosting vs leased hardware etc) the easiest solution might be to try a different server.

**Comment by llomgui** [comment]
Thanks for your replies, The command to continue the import worked.

I didn't try to reduce the number of threads.
