### ISSUE TITLE
Ignore operator on bicycle parking

### ISSUE THREAD

**Issue by uswoods** [openstreetmap/Nominatim#1176]
1. Nobody ever searches for a parking spot for his bicycle with the OpenStreetMap.org website. I think in rare cases a app is being used. Most cyclists just look with their eyes.
2. The _operator_ tag is indexed: At big companies like Volkswagen or Benteler all parking spots would have the same operator. In cities all public spaces should have the same operator: So this information is mostly useless.

So please stop indexing them!

**Comment by lonvia** [comment]
It is a common fallacy to infer 'nobody searches for xxx' from 'I never search for XXX'. It is usually wrong.

There are already [exceptions for the operator tag](https://github.com/openstreetmap/osm2pgsql/blob/master/output-gazetteer.cpp#L366). The comment in the code indicates that 'amenity' has only be included for restaurants and fuel stations. It might be worth restricting it to those two values.

**Comment by uswoods** [comment]
@lonvia Someone has made a small survey for me. Some people indeed look for car parking, but NOBODY searches for bicycle parking. Or do you?

See https://forum.openstreetmap.org/viewtopic.php?id=63817

**Comment by ThomasBarris** [comment]
> @lonvia Someone has made a small survey for me. Some people indeed look for car parking, but NOBODY searches for bicycle parking. Or do you?
> 
> See https://forum.openstreetmap.org/viewtopic.php?id=63817

That is basically not true - [see](https://forum.openstreetmap.org/viewtopic.php?pid=716797#p716797)

**Comment by uswoods** [comment]
@ThomasBarris Don't forget to notice "Ist aber eher selten."

**Comment by mmd-osm** [comment]
I believe this survey is somewhat biased, as is explicitly mentions: do you look for a bike parking _before using a bike_. It disregards all use cases, where I want to search for a bike parking without actually using a bike. As an example, people might be into infrastructure planning or tourism management, and use this information to assess an area.

**Comment by lonvia** [comment]
As amusing as this discussion is, please stop here. There is always somebody who finds certain features useful. I will not remove existing features unless you can prove that including them makes search significantly worse in general. I know that operator tags can be problematic in that way, which is why I haven't closed this ticket yet. It is reasonable to ask to exclude them and I will do something about it when I find a minute. After this is done, you'll likely never encounter a bicycle parking again unless you specifically search for them (although I can't say for sure because you did not bother to report which search did yield so bad results that you demand this immediate removal of all parkings).

I've change the title to reflect what I just said.

**Comment by lonvia** [comment]
operator fix will go live in a couple of hours. Please note that the database will not be reimported. The fix will only gradually have an effect as OSM data is updated.
