### ISSUE TITLE
allow searching airports by iata code

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/Nominatim#1204]
https://wiki.openstreetmap.org/wiki/Key:iata?uselang=en is an useful code, widely used to identify airports

Unfortunately for example https://www.openstreetmap.org/search?query=GRO is not listing https://www.openstreetmap.org/relation/6740225 (with iata=GRO) as one of results

**Comment by lonvia** [comment]
This key is parsed and used. It just happens that 'GRO' again clashes with on of the abbreviations and is shortened to 'GR', which matches against a lot of things. This can unfortunately only be fixed with a complete rewrite of the normalization and abbreviation handling. This is now covered in ticket #1208. Closing here.
