### ISSUE TITLE
Importing planet-latest.osm.bz2 into nominatim is slow

### ISSUE THREAD

**Issue by Snickbrack** [openstreetmap/Nominatim#1234]
Hi,

is it normal that my server is importing the planet-latest.osm.bz2 at the following rate?

Processing: Node(817970k 8.4k/s) Way(0k 0.00k/s) Relation(0 0.00/s)

According to [this ](https://wiki.openstreetmap.org/w/images/thumb/e/e3/Osmdbstats2.png/800px-Osmdbstats2.png)the total node count is 4 billion and im at the above value after three days. So the process on importing takes more than months...

Server specs are:
Intel Core i7-3770
2x HDD SATA 4,0 TB Enterprise
4x RAM 8192 MB DDR3

Can I speed up the process?

PS: What does k mean? 1k = 1000 Nodes?

**Comment by mtmail** [comment]
1k is 1000. 

My last finished planet import showed
```
Node(4759851k 5207.7k/s) Way(527655k 117.10k/s) Relation(6140360 3788.01/s)
Osm2pgsql took 7208s overall
```
That's about 2 hours. And the osm2pgsql step is a relative small part in the whole setup, the indexing that follows takes 10-20x as long.

My server is more powerful but you should be able to finish this step below 6-8h, otherwise you're looking at total setup time of two weeks.

More hardware helps, especially fast harddrives. SSD or NVM drives for all the random disc access. Build-in, not network mounted. Bare metal, not virtual machines. Of course you should follow the postgresql optimizations listed in (https://nominatim.org/release-docs/latest/admin/Installation/) and check general system load, e.g. is all RAM used up and swapping to disk?

**Comment by Snickbrack** [comment]
@mtmail yeah, I know that 1k is 1000 but what is the value? 1000 of what? Apples? Eggs?

Yeah I am know looking at the index step of the germany part which I am now importing.

This is the part which I am mainly need and do the full planet import afterwards.

Thanks for the information my process was at 2 Million and needed just two more? :D

Oh boy...

**Comment by Snickbrack** [comment]
@mtmail yeah, I know that 1k is 1000 but what is the value? 1000 of what? Apples? Eggs?

Yeah I am know looking at the index step of the germany part which I am now importing.

This is the part which I am mainly need and do the full planet import afterwards.

Thanks for the information my process was at 2 Million and needed just two more? :D

Oh boy...

**Comment by mtmail** [comment]
Almost 5 billion nodes and half a billion ways are read (less are written to the database). For the full planet the database will be around 650GB though over time expect it to grow to 700GB (index bloat after many incremental data updates). The fastest complete planet import I've seen was about 2 days on expensive hardware. The highest impact during import and later query speed have SSD drives.
