### ISSUE TITLE
place=quarter not taken into account

### ISSUE THREAD

**Issue by pbnoxious** [openstreetmap/Nominatim#1240]
At the moment Nominatim does not seem to take "place=quarter" into account when processing the administrative surroundings of a searched object. As the [wiki for the place tag](https://wiki.openstreetmap.org/wiki/Key:place) suggests this key in between suburb and neighbourhood it is frequently used.

Not processing this leads to some errors: When only a quarter without any neighbourhoods is tagged, searching for a place in it will incorrectly give it as belonging to an adjacent neighbourhood. 

As an example consider this [adress](https://nominatim.openstreetmap.org/details.php?place_id=31110540), which is directly next to the [quarter node of the "Komponistenviertel"](https://www.openstreetmap.org/node/3407235348) but is instead considered belonging to the ["Edelsteinviertel"](https://www.openstreetmap.org/node/2613855487) which is some kilometres away, but tagged as a neighbourhood.

I am not sure how the issue with not having any neighbourhoods could be solved, but at least processing the quarter might be a good start.

**Comment by mtmail** [comment]
The wiki page https://wiki.openstreetmap.org/wiki/Tag%3Aplace%3Dquarter "A quarter is a named, geographically localised place within a suburb of a larger city or within a town which is bigger than a neighbourhood"
so looking at https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=3407235348&class=place the addressrank of 29 seems wrong. It should be in the range 20-22.

**Comment by lonvia** [comment]
We don't currently have any ranks left between suburb(20) and neighbourhood(22). So adding quarter in a way that is in line with the wiki description would mean that we have to demote neighbourhood  to rank 24. Possible but I need to have a look at the data, what the exact effects of such a change would be.

Just to be clear: adding place=quarter in that way would do nothing to 'remove' the neighbourhood from the example address. Nominatim searches for the closest node for each rank level. The result would be that it adds the Komponistenviertel and the Edelsteinviertel both to the address.

If they are actually on the same administrative level, they should have the same place designation.

If they are not because there is no 'neighbourhood' in the Komponistenviertel, then only adding exact areas for the quarter and/or the neighbourhood will help. Using only nodes for places will always force Nominatim to make educated guesses of what belongs where.

**Comment by arvindkartik** [comment]
Since 'quarter' is not mentioned in the address_levels.json, it is imported as address rank 29 and rank 30. This causes problems in reverse geocoding where a far away quarter is returned even when nearby location data is available, because the geometry of the quarter contains the geocoded coordinate. 

For example, take a look [at this reverse geocoding response.](https://nominatim.openstreetmap.org/reverse.php?format=html&lat=45.43775653103832&lon=9.193453788757326&zoom=18)

**Comment by lonvia** [comment]
Added at the same level as neighbourhood for now.
