### ISSUE TITLE
error connecting to Nominatim webservice

### ISSUE THREAD

**Issue by FernwoodRuben** [openstreetmap/Nominatim#1249]
Hi folks, 

I am getting this message "error connecting to Nominatim webservice"  when I try to geocode addresses using ODL studio. Is this really a problem with Nominatim, or more likely a problem with me?

Thank you.

**Comment by mtmail** [comment]
Assuming the connection goes to http://nominatim.openstreetmap.org Likely your IP address got auto-blocked when too many requests in short time happened, see https://operations.osmfoundation.org/policies/nominatim/ It un-blocks automatically.

**Comment by lonvia** [comment]
If ODL is a vehicle tracker, then it is likely that it is permanently blocked because the software in general is in violation of our usage policy.

In any case, this would be an operational issue and this issue tracker is the wrong place to report it. I recommend asking customer support for your software.

**Comment by FernwoodRuben** [comment]
Thanks mtmail, I will keep trying then. 
Ionvia, ODL Studio is a route planner, not a vehicle tracker. 

Thanks for your help folks.
