### ISSUE TITLE
error: peer's X.509 certificate is untrusted: where do I get a new one ?

### ISSUE THREAD

**Issue by hotteflash** [openstreetmap/Nominatim#1299]
Hello,

I'use nominatim.openstreetmap.org in SAP system to get geodata,
but now I get error:
SSL handshake with nominatim.openstreetmap.org:443 failed:
SSSSLERR_PEER_CERT_UNTRUSTED - the peer's X.509 certificate is untrusted SSL read failed

Where/how do I get this cerificate ?

Thanks 

Hotte

**Comment by mtmail** [comment]
https://answers.sap.com/questions/201358/ssl-problem-when-connecting-to-a-third-party-rest.html and https://answers.sap.com/questions/217400/500-ssl-peer-certificate-untrusted.html suggest
"You need to import the certificate chain of the CA that signed the certificate."

One way is to go to https://www.ssllabs.com/ssltest/analyze.html?d=nominatim.openstreetmap.org&latest On the result page look for the section "Certification Paths". On the right side you'll find an icon, gray on gray, to download the certificate chain.

![image](https://user-images.githubusercontent.com/3727288/52339250-e1561500-2a0c-11e9-8db3-fa8e0e99c446.png)

How that is done is best asked on SAP forums.

**Comment by SomeoneElseOSM** [comment]
I'm guessing that whatever SAP is using to access Nominatim is using an old version of Java.  I'd actually suggest updating that to a current version (if the SAP product supports it) as per https://www.openstreetmap.org/user/Cascafico/diary/47625#comment44054 .  If that's not an option then the cacerts workaround described in that diary entry may work (but check your support agreement with SAP/whoever to make sure you're not doing anything that you shouldn't).

Since you're using SAP (which isn't exactly cheap at the best of times) it probably also makes sense to mention https://operations.osmfoundation.org/policies/nominatim/ and rattle the tin in the direction of https://donate.openstreetmap.org/ :)
