### ISSUE TITLE
South Harwich, MA zip code

### ISSUE THREAD

**Issue by jwk231** [openstreetmap/Nominatim#1300]
I searched for the following address: 2 Lakehurst Drive, Harwich MA.  There was one error in the results returned: the Zip code.  OSM returned 02661 as the zip code.  That zip code is not valid for >>any<< street address.  It is the zip code for mail boxes at the South Harwich Post Office >>only<<.  The correct zip code for this address is 02645.

**Comment by lonvia** [comment]
This ZIP code comes from the Tiger data which insists that quite a few streets in the area are assigned this postcode.

In general, the postcode is a guess because the exact address is not yet in OpenStreetMap. To get exact address results, the addresses need to be mapped in the area.

Closing because it is a data issue.

**Comment by jwk231** [comment]
Thanks for the clarification.  Looks like the Census Bureau isn't using zip
codes consistent with the USPS's definitions.  It has been an ongoing issue
for my address.  Now I know why.
