### ISSUE TITLE
Installing update and other data issues

### ISSUE THREAD

**Issue by stevewolfe555** [openstreetmap/Nominatim#1331]
Hello,

I am hoping these are quick simple issues:

1. Tiger database - running this command didn't seem to do anything `./utils/imports.php --parse-tiger <tiger edge data directory>` I changed the DIR to where i have my install and ran from the build dir as the nominatim user.

2. I and been doing this over the course of a couple of months and now want to update. Its a full planet install. What url will work for this, currently I have it set to target this one. https://planet.openstreetmap.org/replication/day though im not sure its correct.

3. I have been following the install update guide on ubuntu 18 and im down to the part where I try to run the first update. `./utils/update.php --init-updates` and i am getthing the error  `ERROR: pyosmium-get-changes not found or not usable`

Now I ran `sudo apt-get install python-pyosmium` and ` pip install --user nominatim` but I can't seem to find any users files that contain the `/home/user/.local/bin/pyosmium-get-changes`  im guessing im installing that last command wrong but can't see where Im going wrong.

Hoping you can help.

Many thanks 

Steve

**Comment by mtmail** [comment]
Hi Steve,

Which version of Nominatim do you use? Is it different from the version originally installed? I assume http://nominatim.org/release-docs/3.1.0/ I'm just double-checking, you don't need to upgrade to the newest version.

1. In the latest version we moved the `parse-tiger` into a separate script, see http://nominatim.org/release-docs/develop/data-sources/US-Tiger/ Instead of dealing with the TIGER Edge files (`*_edges.zip`) you can now download the already parsed/converted files from https://nominatim.org/data/tiger2018-nominatim-preprocessed.tar.gz Then places the `*.sql` files into `Nominatim/data/tiger` and run `./utils/setup.php --import-tiger-data`.

2. That URL works. Updating one day takes several hours (as usual depending on hardware). If you're several months behind it might take weeks to catch up. The script can run in the background, takes only CPU core and won't interrupt queries, it will be just slow. It's faster to delete the database and do a full import. Well, if your users are fine with the downtime.

3. Not sure where apt places the file when you install it via `apt-get`. Try `sudo su nominatim; pip install --upgrade pip; pip install --user osmium`. (The `--user` means files get installed in the `~/.local` directory, it doesn't set the user to be osmium).

**Comment by stevewolfe555** [comment]
Hi thanks for the reply.

1. I followed steps 1-5 which all worked http://nominatim.org/release-docs/latest/admin/Import-and-Update/#installing-tiger-housenumber-data-for-the-us are you saying i can now the skip steps 1 & 2 after that?

2. It took about a month to run the full planet install on my server. Not sure why, I don't have ssds but I do have 64gb ram and 12 cpu cores. Its might have been the raid but i would rather see if the updates will catch up quicker.

3.  all those commands ran just still no home / local DIR.

**Comment by stevewolfe555** [comment]
3. found it

**Comment by stevewolfe555** [comment]
Update command runs now, I think the country link i send is incorrect. Can you show me the right one please?

2. ERROR: HTTP Error 404: Not Found
Done. Database updates will start at sequence 2308 (2019-01-06T22:59:47Z)

**Comment by mtmail** [comment]
1. Yes, the /release-docs/latest/ URL describes Nominatim version 3.2. On the /release-docs/develop/ URL you can see it's now one step less http://nominatim.org/release-docs/develop/admin/Import-and-Update/#installing-tiger-housenumber-data-for-the-us

2. Makes sense to run the updates, it will eventually catch up. Two months behind should be managable.

> ERROR: HTTP Error 404: Not Found

That might possibly happen in `lib/lib.php` `getDatabaseDate()`. But I see it sets a sequence number so I think it's fine. You should see an entry in the `import_status` table now.

Good luck running the updates. You can kill the update script anytime, it will simply start again from the last `import_status` date and update that date regularly.

**Comment by stevewolfe555** [comment]
Do I have to point the importer to a specific version?

currently, I am getting this response.

`~/.local/bin/pyosmium-get-changes --server https://planet.openstreetmap.org/redaction-period/day-replicate/ -o /srv/nominatim/Nominatim-3.2.0/build/osmosischange.osc -s 30 -I 162`

**Comment by mtmail** [comment]
What does the `import_status` table contain? Mine for example contains the single row

```
$ psql nominatim
# select * from import_status;
   lastimportdate    | sequence_id | indexed
---------------------+-------------+---------
 2019-03-15 23:59:00 |        2376 | t
```

The `./utils/update.php --init-updates` should've looked up the relevant `sequence_id`. You said it reported an error due to `pyosmium-get-changes` missing. Maybe rerunning is all you need.

If that doesn't work the way to find the correct sequence_id manually is to find the date of the latest imported node_id `select max(osm_id) from place where osm_type = 'N';` See getDatebaseDate() in https://github.com/openstreetmap/Nominatim/blob/master/lib/lib.php With the date you can then look for the right *.state.txt file in https://planet.openstreetmap.org/replication/day/000/002/ which in turn has an entry like `sequenceNumber=2320`.

**Comment by stevewolfe555** [comment]
I have one rwo too.

`   lastimportdate    | sequence_id | indexed
---------------------+-------------+---------
 2019-01-07 01:59:47 |         162 | t
(1 row)`

**Comment by mtmail** [comment]
I have never seen the URL `https://planet.openstreetmap.org/redaction-period/day-replicate/000/000/` before, or documentation listing it. That data set was last used updated 2012 https://planet.openstreetmap.org/redaction-period/day-replicate/000/000/

Your `build/settings/local.php` should contain something like
```
  @define('CONST_Pyosmium_Binary', '/srv/nominatim/.local/bin/pyosmium-get-changes');
  @define('CONST_Replication_Url', 'https://planet.openstreetmap.org/replication/day');
  @define('CONST_Replication_MaxInterval', '40000');     // Process each update separately, osmosis cannot merge multiple updates
  @define('CONST_Replication_Update_Interval', '86400');  // How often upstream publishes diffs
  @define('CONST_Replication_Recheck_Interval', '900');   // How long to sleep if no update found yet
```
