### ISSUE TITLE
How to get maps without creating own tile-server?

### ISSUE THREAD

**Issue by Zakrinichniy** [openstreetmap/Nominatim#1391]
I'm sorry for asking, but can you help me with this problem?

**Comment by mtmail** [comment]
It's not possible, Nominatim doesn't contain data needed to create map tiles.

**Comment by Zakrinichniy** [comment]
So only option is to set up tile server like Mapnik?
I thought there are some values in conf files to provide map tiles.

**Comment by mtmail** [comment]
http://nominatim.org/ is a search engine to find places, it can't create map tiles.

**Comment by matkoniecz** [comment]
> I'm sorry for asking, but can you help me with this problem?

This is an issue tracker for Nominatim. To quote readme

> Nominatim (from the Latin, 'by name') is a tool to search OpenStreetMap data by name and address (geocoding) and to generate synthetic addresses of OSM points (reverse geocoding). 

It is not a place to get help with questions like "How to get maps without creating own tile-server"

**Comment by mtmail** [comment]
Closing here because I don't see the connection to the Nominatim software.

The website is a bit old but https://switch2osm.org/serving-tiles/ has a guide to install a tile server. 

https://help.openstreetmap.org/ might be a good place to ask more generic questions, e.g. which tools to use or if there are alternative tile servers.
