### ISSUE TITLE
POIs do not inherit addr:street from their building correctly

### ISSUE THREAD

**Issue by jose1711** [openstreetmap/Nominatim#1395]
If I do a search for "Rontgenova 1" the first result returned is a fast_food amenity way off the actual location even though an exact address exists in OSM db: https://nominatim.openstreetmap.org/search.php?q=rontgenova+1&polygon_geojson=1&viewbox=

It looks like from a nearby location only housenumber information (1) is taken.

**Comment by lonvia** [comment]
It would help if you could tell what the expected result is.

**Comment by jose1711** [comment]
sure. the correct (and expected) result is https://www.openstreetmap.org/node/4735168370#map=18/48.12868/17.10425 - currently the 4th result. seeing an amenity that is 700 m far and on a completely different address (Kopcianska 1 - see a nearby relation on a building) as the first (hence presented as the most accurate result) is completely wrong.

**Comment by jarek** [comment]
Looks like this might be because the building https://www.openstreetmap.org/relation/1922225 which is the only thing with "Röntgenova 1" address tags is tagged with `addr:conscriptionnumber=3392`, `addr:housenumber=1`, `addr:street=Röntgenova`.

Nominatim interpretation is https://nominatim.openstreetmap.org/details.php?place_id=198712458, it constructs `place:house_number=3392/1`.

Should https://wiki.openstreetmap.org/wiki/Key:addr:conscriptionnumber be prepended to the house number like that?

**Comment by jose1711** [comment]
Thank you, that would indeed explain such behavior. Conscriptionnumber and streetnumber tags are specific to Czech Republic and Slovakia. As no one really uses conscriptionnumber for searches and housenumber contents is not 100 % standardized (sometimes it mirrors streetnumber, sometimes it contains conscriptionnumber + "/" + streetnumber) I think it would make sense that streetnumber tag overrides housenumber when constructing place:house_number. Would that be possible?

**Comment by andrewshadura** [comment]
Nominatim’s interpretation is correct (I have requested it), but then it should rank it first as the full match, not the last as a partial match. @lonvia, what do you think can be done?

**Comment by lonvia** [comment]
Alright, so "Rontgenova 1" is not the reported issue. Your issue is actually that the fast food has the wrong address. Sorry, I got that wrong. That looks indeed like a bug. It should inherit the `addr:street` tag from the train station relation.

I've taken the liberty to adapt the issue title to reflect the internal problem in the code here.
