### ISSUE TITLE
No results when adding postal code to search query

### ISSUE THREAD

**Issue by aoreinoso** [openstreetmap/Nominatim#1403]
"No results when adding postal code to search query" from https://github.com/openstreetmap/Nominatim/issues/650

I think I have the same problem today.

Sample: No resut with "Calle Periodista Francisco de Paula Terrón. Granada 18015" but with ""Calle Periodista Francisco de Paula Terrón. Granada " I have results:
...
"Vía peatonal Calle Periodista Francisco de Paula Terrón, Cerrillo de Maracena, Chana, Granada, Comarca de la Vega de Granada, Granada, Andalucía, 18014, España"

"Vía peatonal Calle Periodista Francisco de Paula Terrón, Cerrillo de Maracena, Chana, Granada, Comarca de la Vega de Granada, Granada, Andalucía, 18015, España"
...

Thanks

**Comment by lonvia** [comment]
Nominatim is having trouble with such long addresses without any comma separation. Please use commas to improve the search result. [Calle Periodista Francisco de Paula Terrón, Granada 18015](https://nominatim.openstreetmap.org/search.php?q=Calle+Periodista+Francisco+de+Paula+Terr%C3%B3n,+Granada+18015) works perfectly fine.

That said,  this should be working anyway because we have a perfect match to the long street name here. I fear that due to some optimisation the perfect search candidate is thrown out early. I need to investigate how to avoid this.
