### ISSUE TITLE
macos install: "No appropriate byteswap found for your system"

### ISSUE THREAD

**Issue by samelie** [openstreetmap/Nominatim#1434]
System info: `macos 10.14.5`
Sucessfully ran `cmake ..` but get `nominatim/postgresql.h:19:2: error: "No appropriate byteswap found for your system."` during `make`

Any ideas?

**Comment by mtmail** [comment]
I get the same on my MacOS. Probably the `endian.h` is in a different path. It's unlikely to be fixed soon, and I suspect there will be further error in the installation later because all scripts were written with Ubuntu/CentOS or similar in mind. Can you try the installation inside a Linux virtual machine?

**Comment by lonvia** [comment]
I second @mtmail here. We don't have the capacity to officially maintain MacOS support. If you do get Nominatim to run on MacOS, a PR for the necessary changes is welcome but we can't really help with the work. Sorry about that. Closing as won't fix.
