### ISSUE TITLE
Queries doesn't work?

### ISSUE THREAD

**Issue by theAlinux** [openstreetmap/Nominatim#1451]
this two page i did

1- https://nominatim.org/release-docs/develop/appendix/Install-on-Ubuntu-18/
2- https://nominatim.org/release-docs/develop/admin/Import-and-Update/

but wikipedia articles import get error

![Ekran Alıntısı1](https://user-images.githubusercontent.com/10341948/62428517-6b0c4400-b70b-11e9-9ba3-20b95b4d2ff0.PNG)

after /nominatim page this work

![Ekran Alıntısı](https://user-images.githubusercontent.com/10341948/62428523-7c555080-b70b-11e9-988b-df57bcfa5e0d.PNG)

but queries doesn't work, why didn't happen? also i work over google compute engine

**Comment by mtmail** [comment]
As the screenshot says "server closed the connection unexpectedly". Server in this case is the database server. Check the postgresql log files. It probably crashed. Often the reason is not enough memory, but it could also be a network issue if the database or storage is on another machine.

Geocoding queries don't work until the installation finished.

**Comment by theAlinux** [comment]
> As the screenshot says "server closed the connection unexpectedly". Server in this case is the database server. Check the postgresql log files. It probably crashed. Often the reason is not enough memory, but it could also be a network issue if the database or storage is on another machine.
> 
> Geocoding queries don't work until the installation finished.

actually installation done just wikipedia articles import get error "erros ignore restore: 3"

you say if you ram upgrade it will work, i'm try

**Comment by theAlinux** [comment]
i'm upgrade ram 7.5 gb to 15 gb done, thanks :)
