### ISSUE TITLE
Wrong suburb data - New Zealand

### ISSUE THREAD

**Issue by quyn-argus** [openstreetmap/Nominatim#1462]
This coordination -37.20841 174.91362 is reversed as Buckland which is a wrong suburb
40, Crosbie Road, **Buckland**, Franklin, Auckland, 2120, New Zealand (House)

[https://nominatim.openstreetmap.org/search.php?q=-37.20841+174.91362&polygon_geojson=1&viewbox=]

However, clicking on Details, the suburb is shown correctly as **Pukekohe** in the Address tag. Please help update the database.

Address Tags | 40 (housenumber)Crosbie Road (street)**Pukekohe** (suburb)
-- | --

**Comment by lonvia** [comment]
Pukehoe only exists as a [node](https://www.openstreetmap.org/node/71364807), so the address always tends to be guess work until the full area of Pukehoe is mapped in OSM. The problem here though is rather that Frankiln overwrites Pukehoe because Nominatim considers them at the same level. Might need #213 for fixing as well.

**Comment by lonvia** [comment]
Closing here in favour of #213.
