### ISSUE TITLE
Isolated dwelling name in address instead of farm

### ISSUE THREAD

**Issue by markuskallander** [openstreetmap/Nominatim#1465]
Fetching address for a farm will return the name of the closest isolated_dwelling as suburb, and not the name of the farm itself. To me this seems wrong... Ex: https://www.openstreetmap.org/search?whereami=1&query=59.07182%2C16.31292#map=17/59.07182/16.31292

**Comment by lonvia** [comment]
You get back the address of the street not the farm at that level. https://www.openstreetmap.org/search?whereami=1&query=59.07182%2C16.31292#map=14/59.0718/16.3129 works as you would expect.

The problem here is that the street is quite long but can only have one address and in this case the village down the road won. That's a known issue, see #328. Closing in favour of that.

**Comment by markuskallander** [comment]
I noticed that the address changed when the far away dwelling was changed from a point to an area, is that a symptom of the same issue?

**Comment by lonvia** [comment]
Ah, I have to slightly correct myself. Farms are in general not considered part of an address. That's why it does not show up in the displayed address. The isolated dwelling is then the closest around. I've meant to reduce the search area for those, see #575 but never got around to do this until now. When done it should fix your issue though, in that Granhammar isn't in the address anymore. The farm still won't show up.

**Comment by markuskallander** [comment]
It's fine that the farm is not part of the address I guess, but why did an isolated dwelling disappear from the address when I changed it from a point to a an area? Is it expected behaviour? @lonvia
