### ISSUE TITLE
Switzerland. Wrong Locations

### ISSUE THREAD

**Issue by lobosinf** [openstreetmap/Nominatim#1471]
If you enter "Libellenweg Küssnacht am Rigi" there is no match.
If you enter "Libellenweg Küssnacht" a match will be found.

In fact, there is no street "Libellenweg" in "Küssnacht". The correct address is in "Küssnacht am Rigi" so the user would expect to get a match when he enters "Libellenweg Küssnacht am Rigi".

**Comment by mtmail** [comment]
The train station (https://www.openstreetmap.org/node/2074359564) has the name "Küssnacht am Rigi" but the village itself (https://www.openstreetmap.org/node/240042568 and https://www.openstreetmap.org/relation/1683087) got renamed (first sentence on https://de.wikipedia.org/wiki/de:Küssnacht SZ). Is that a simple typo in the old_name on https://www.openstreetmap.org/node/240042568 ?

**Comment by lobosinf** [comment]
Thanks for the quick reply... Well, in terms of Wikipedia this article might be correct for the political system but not for the postal code and the the towns. Just have spoken to the swiss postal office. There is officially no postal code/town "6403 Küssnacht" -> Correct is always "6403 Küssnacht am Rigi". Therefore all streets wich are mapped with "Küssnacht" should also shown up when entering "Küssnacht am Rigi".

**Comment by mtmail** [comment]
I fixed the typo on the node ("Küsnacht am Rigi" => "Küssnacht am Rigi") and changed the tag `name:old` to `old_name` (https://wiki.openstreetmap.org/w/index.php?title=Key:name&uselang=en-US)

A bit confusing to have a boundary`admin_level=8` https://www.openstreetmap.org/relation/1683087 on top of a `admin_level=6` https://www.openstreetmap.org/relation/1688587 but they represent different things (city, Bezirk/district) and point to different wikipedia pages so that's probably alright.

The city has the normalized name keywords `kussnacht a rigi` now https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=1683087&class=boundary&keywords=1 that's good. But the street doesn't have the normalized address keyword `kussnacht a rigi` yet https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=34322029&keywords=1 I'd say we need to wait for the street to be reindexed, I don't have that admin power to the server.

**Comment by lobosinf** [comment]
It really is a bit confusing with "Küssnacht" and "Küssnacht am Rigi"... But the postal service doesnt keep the town "Küssnacht" in their directory any more. Its all on "Küssnacht am Rigi"
Thanks very much for the quick reaction... Ill have a look at it next week!

**Comment by lonvia** [comment]
Please note that Nominatim does not return postal addresses, it returns the geographic location description so to speak.

Closing as data issue.

**Comment by lobosinf** [comment]
I understand this issue... but:
If you enter an address in your business software you must enter this address so that the postal service can deliver your mail. Therefore you enter the correct postal code with town -> 6403 Küssnacht am Rigi.
What we expect now is, that the nominatim service returns us the GEO-Coordinates ... even you have just 6403 Küssnacht in your database. The service should give us the same location back ... no matter if you enter "6403 Küssnacht" or "6403 Küssnacht am Rigi".

**Comment by mtmail** [comment]
These return the same street (https://www.openstreetmap.org/way/34322029):

https://nominatim.openstreetmap.org/search.php?q=Libellenweg+K%C3%BCssnacht+am+Rigi
https://nominatim.openstreetmap.org/search.php?q=Libellenweg+K%C3%BCssnacht

These return the same village (https://www.openstreetmap.org/node/240042568):

https://nominatim.openstreetmap.org/search.php?q=6403+K%C3%BCssnacht
https://nominatim.openstreetmap.org/search.php?q=6403+Küssnacht+am+Rigi
