### ISSUE TITLE
Import stack on creating search indexes

### ISSUE THREAD

**Issue by juggernautt** [openstreetmap/Nominatim#1476]
I'm importing planet file to database, not binary file. 3 days before setups script started to create search indexes. Since then nothing changed, no errors, no changes. 
From your experience do I have to wait more or is it stack?
I'm running this import with 128GB Ram  and 2TB SSD.

**Comment by mtmail** [comment]
I've seen this before. On the postgresql database run
```
SELECT pid,
       usename,
       pg_blocking_pids(pid) AS blocked_by,
       query AS blocked_query
FROM pg_stat_activity; 
```

If you see a line
```
 pid  |  usename  | blocked_by | blocked_query
-------+-----------+------------+---------------------------------------------------------------------------
 99441 | nominatim | {100472}   | CREATE INDEX idx_placex_rank_search ON placex USING BTREE (rank_search) ;
```
and the blocked_by pid points to an autovacuum process it's save to stop the autovacuum process. Otherwise it will go on forever (well at least very very long)

E.g.
```
SELECT pg_terminate_backend(100472) FROM pg_stat_activity; 
```

You might need to watch and repeat this another 3-5 times. With your hardware the searchindex creation step shouldn't take longer than 3 hours total.

**Comment by juggernautt** [comment]
Thanks for your answer,
There is query result:
pid  |  usename  | blocked_by | blocked_query
 22939 | nominatim |   {} | DEALLOCATE pdo_stmt_0000000c                
13150 | nominatim | {}  | CREATE INDEX idx_search_name_centroid ON search_name USING GIST (centroid) ;
5675 | nominatim | {}  | SELECT pid, usename, pg_blocking_pids(pid) AS blocked_by, query AS blocked_query FROM pg_stat_activity;

I guess empty brackets means nothing is blocked. Or I'm missing something?

**Comment by MatthiasLohr** [comment]
Thanks, this issue helped a lot!
