### ISSUE TITLE
No result when postalcode is added to city

### ISSUE THREAD

**Issue by JLuc** [openstreetmap/Nominatim#1509]
https://nominatim.openstreetmap.org/?city=Bonneveau gives the result :
> Bonneveau, Vendôme, Loir-et-Cher, Centre-Val de Loire, France métropolitaine, 41800, France
> `Computed Postcode` is `41800` 
> `Address Tags` is `41800 (postcode)`

Same when asking with bulk query : 
https://nominatim.openstreetmap.org/search.php?q=Bonneveau+41800

But structured query with city and postalcode gives no result at all : 
> https://nominatim.openstreetmap.org/?city=Bonneveau&postalcode=41800

**Comment by JLuc** [comment]
Same with 

https://nominatim.openstreetmap.org/?postalcode=10000&city=Troyes : no result
and
https://nominatim.openstreetmap.org/?city=Troyes : result with postcode=10000

**Comment by lonvia** [comment]
The computed postcode is currently not in the search index, so we cannot directly search for it. We'd need a separate column in `search_name` for it.

**Comment by JLuc** [comment]
Thanks for caring this ticket. I dont understand your answer because postcode actualy has an effect on the search : in these shared examples it *prevents* to get the result.

**Comment by lonvia** [comment]
The other queries just work accidentally because the postcode is interpreted as a house number which may be omitted (it's actually an accident that should be fixed because it causes bad results in other cases). As a general rule city+postcode is a combination that Nominatim does not do well at. There is already another ticket about that (#1028), which I just saw that you are very well aware of it. Nothing has changed since then, so no need to open new tickets about the same issue.

Closing as duplicate.
