### ISSUE TITLE
Address not found

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/Nominatim#1520]
Sorry for not providing a better title, I have no idea what is going wrong in this case.

`Obrońców Modlina 5, Kraków` https://www.openstreetmap.org/search?query=Obro%C5%84c%C3%B3w%20Modlina%205%2C%20Krak%C3%B3w#map=17/50.03714/20.00800&layers=D

`Obrońców Modlina 5` https://www.openstreetmap.org/search?query=Obro%C5%84c%C3%B3w%20Modlina%205#map=18/52.43602/20.66503

is unable to find `addr:street=Obrońców Modlina addr:housenumber=5` https://www.openstreetmap.org/way/155655042#map=19/50.03791/20.00873

I run this area through JOSM validator but found only bug in JOSM validator itself ( https://josm.openstreetmap.de/ticket/18219#ticket ) and some road topology issues.

**Comment by lonvia** [comment]
The building was not indexed in Nominatim at all, likely because it used to have a broken geometry. If the geometry was fixed by moving a node around then Nominatim wouldn't pick up the change. Node changes are not propagated to ways for efficiency reasons.

I've now forced a reimport and all is well.
