### ISSUE TITLE
Our addresses on Open Street Map include a suburb that is not part of the address.

### ISSUE THREAD

**Issue by djkizza** [openstreetmap/Nominatim#1535]
We have just noticed that every address in our local area on Open Street Map includes the street address, the suburb but then lists a second suburb that is about 30 minutes away.  We dont know why the second suburb was included, but it seems to be on the entire area, not just certain things.  We were just wondering if there's anyway to remove the second suburb from the address?

I've attached a photo that shows the issue.  This address should be Kurwongbah Rd, Petrie QLD, 4502.  Not Caboolture.  However, Caboolture is included on all of our addresses in the area including nearby suburbs as well.
![OSM](https://user-images.githubusercontent.com/57020835/67608623-6916c600-f7cc-11e9-94d9-422e1c7db477.jpg)

**Comment by mtmail** [comment]
https://nominatim.openstreetmap.org/search.php?q=Kurwongbah+Park+Nature+Refuge&polygon_geojson=1 returns the address "Kurwongbah Drive, Petrie, Caboolture, Queensland, 4502, Australia"

https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=6987350&class=natural lists what Nominatim considers to be the address components.

You're saying Caboolture (city) should not be part of the address, you're right it seems too far off.

In the OpenStreetMap world we often have to deal with incomplete data. In other words sometimes Nominatim has to make guesses. Here a step forward would be if Caboolture was mapped as boundary (OSM relation) instead of center point (OSM node, https://www.openstreetmap.org/node/2506724881). https://en.wikipedia.org/wiki/Caboolture,_Queensland gives hints on where roughly the edges of the city are.

There's not a single place to report data issues on OpenStreetMap. Usually we point to learning how to edit the map or leave a note on the map to a local mapper (https://www.openstreetmap.org/fixthemap) but city relations are pretty advanced for a first time mapper. The Australian OSM community has a mailing list https://lists.openstreetmap.org/listinfo/talk-au you could contact, they also seems to have an IRC channel https://wiki.openstreetmap.org/wiki/IRC
