### ISSUE TITLE
hamlet outside of city being linked to many places inside city

### ISSUE THREAD

**Issue by r00t-** [openstreetmap/Nominatim#1613]
in my city, a large amout of  places are being associated with a small "hamlet" that is located tens of kilometers away, outside of the city (and thus completely irrelevant).
i'm wondering if this is a bug or a mapping error.

some of thousands of examples:
https://nominatim.openstreetmap.org/details.php?place_id=134431770
https://nominatim.openstreetmap.org/details.php?place_id=198861432

these are being associated, at level 16, with https://www.openstreetmap.org/node/4982471205 ,
which is tens of kilometers away

**Comment by r00t-** [comment]
(might be a duplicate of #1505 , but not sure)

**Comment by mtmail** [comment]
There's one difference. In Bremen there's an admin_level=9 (Stadtbezirk Bremen Ost).

"Parts of a municipality with parish councils / self government (Stadtbezirk / Gemeindeteil mit Selbstverwaltung) " https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative#10_admin_level_values_for_specific_countries

In the address list
https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=249003334&class=highway
the place:hamlet should be skipped because the hamlet is inside the admin_level=9.

Also interesting how the Stadtbezirk is sorted higher even when looking at the hamlet only
https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=4982471205&class=place

We have a bit of control in the newest version of Nominatim with a generic list and per-country settings (further down in the list)
https://github.com/openstreetmap/Nominatim/blob/master/settings/address-levels.json

**Comment by r00t-** [comment]
@mtmail:
thanks for your analysis.

are you saying that this is already fixed in recent versions,
or are you saying that in recent versions it could be fixed with configuration settings?

i actually set up my own nominatim instance,
using master as of Nov 26 (c36896c5) and it has the issue.

can you suggest a specific configuration change i could try?

(otherwise i am personally ok with just filtering "Kuhsiel" from my output...)
i'm only reporting this because it's also on the main site,
and i hope it can be fixed.

**Comment by mtmail** [comment]
I was just rewording what you wrote and adding permanent links (place_id is sequential during a database build and would change when it gets reimported).

http://nominatim.org/release-docs/latest/develop/Ranking/ explains how https://github.com/openstreetmap/Nominatim/blob/master/settings/address-levels.json works. I'd try removing admin_level=9 places like https://github.com/openstreetmap/Nominatim/commit/b8f7b3cc8dfe4da04bf3d4c26cf152dc0886665d Well, first check in Germany where admin_level=9 is used (overpass turbo), I assume only big cities.

**Comment by lonvia** [comment]
place=hamlet got demoted in d732dc3bb287bbbc58da28a637cef3dc2cc4802e. Now that the database has been reimported, the changes should be visible. @r00t-, could you please check if that issue is solved for you?
