### ISSUE TITLE
Assignment of boundary=political to a street is almost random

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/Nominatim#1655]
Search for Tenerife (https://nominatim.openstreetmap.org/search.php?q=tenerife&polygon_geojson=1)
returns
"Tenerife, Calle Cruz Roja, La Ranilla, Punta Brava, Puerto de la Cruz, Santa Cruz de Tenerife, Canary Islands, 38400, Spain"

The address hierarchy
https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=2108882&class=boundary
shows the island has `rank 29` and get assigned a street/footpath.

The street though isn't in the center of the island and far away from the linked place (role=admin_centre) https://www.openstreetmap.org/node/29015863

On my installations it gets linked to different the streets, e.g. http://www.openstreetmap.org/way/216257202

It causes me trouble on island Fuerteventura. Some installations link it to a different highway (and thus different city than the capital city), lowering the `address_importance` ever so slightly and (as I think second-best result) the capital city now ranks 1.

I tried to give the islands `admin_level=7` (in this state island groups are `admin_level=6`, regions on the islands are `admin_level=8`, nothing had `admin_level=7` yet) and reindex. It had no effect on the rank
```
                          'osm_type' => 'R'
                          'osm_id' => 2214682
                          'class' => 'boundary'
                          'type' => 'political'
                          'admin_level' => 7
                          'rank_search' => 30
                          'rank_address' => 30
```

1. Should a `boundary=political` be assigned to a street? I think it shouldn't. Then again even mountain ranges `boundary=region` like the Alps (https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=2698607&class=boundary) are assigned a street.

2. Should `boundary=political` with `admin_level` set change the `rank`? I think it shouldn't, it's not an administrative level. Wiki says "they are distinct from administrative boundaries so admin_level=* is not applicable."

3. Should `boundary=political` in combination with `political_division` map to `ranks`?

4. Are https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dpolitical#political_division.3D.2A for those island so special it simply doesn't fit a generic data model?

5. Should the islands be mapped both `boundary=political` and `boundary=administrative`? I think so, it would mean having two relations though. The wiki link for  says "Intermediate administrative and geographic boundary (which is also electoral)"

I'm happy doing (5.). But maybe there is possible solution for Nominatim not to assign random streets to larger areas to make results more reproducible.

**Comment by lonvia** [comment]
There's couple of problems coming together here.

`boundary=political` are normally such unimportant features like electoral areas. I really wouldn't want those to show up in any search results unless specifically searched for. I don't know why this tag is used here. From what I read in Wikipedia, the island has its own administration, so `boundary=administrative`+`admin_level=7` looks quite appropriate to me. Doesn't look like there are any comarcas on the Canary Islands. But this is something for the locals to decide.

Even if we keep the `boundary=political`, it shouldn't be the one to show up. Instead you should get [the island](https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=2108882&class=place) which has a much more suitable rank. The problem here is that the importance comes entirely from the wikipedia tag, so it is random what you get back. We could fix this by ensuring that the importance of places with lower rank is still a bit higher (add 0.00001*rank or so).

The place result is better but still not ideal. There is still a town in the address which is wrong. And here we need to add the general rule that the features in the address list should not be smaller than the object they address. This is mostly important for long rivers (e.g. see the rather stupid address for the [Rhine](https://nominatim.openstreetmap.org/details.php?place_id=234655801)) but also for features like national parks, time zones and other boundaries. I thought we already had a ticket about that but I can't find it.

**Comment by mtmail** [comment]
In the wiki history of `boundary=political` it looks like it was created for UK wards, that's smaller areas, first. 2011 it was clarified when administrative and political (election related) boundaries overlap they shouldn't be combined (semicolon separated values). In https://www.openstreetmap.org/relation/1157729 in 2014 Fuerteventura got administrative boundary removed. I don't think the situation can be solved easily, and Nominatim is mostly about administrative hierarchy so closing it here.

I remember a ticket about the Alps, but it was country code filter related https://github.com/openstreetmap/Nominatim/issues/883
