### ISSUE TITLE
Wrong hierarchy for St. Cloud, MN

### ISSUE THREAD

**Issue by iandees** [openstreetmap/Nominatim#1684]
A [reverse geocode for St. Cloud, MN](https://nominatim.openstreetmap.org/reverse.php?format=html&lat=45.57785111332559&lon=-94.18716430664062&zoom=13) says it's in Florida: https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=137238&class=boundary

<img width="332" alt="image" src="https://user-images.githubusercontent.com/261584/74664975-63bafe00-5164-11ea-826a-fc045af6dcd5.png">

What's the best way to correct this connection?

**Comment by mtmail** [comment]
Strange indeed.

On https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=137238&class=boundary you'll see a section 'Linked Placed' and the node points to a different city St. Cloud in Florida.

In Nominatim places are linked when the relation has a remember role `admin_centre` or `label` pointing to a node. I can't see such a member in the relation though. On my local Nominatim installation the link also doesn't exist. Could be it got fixed in the data and Nominatim hasn't correctly removed the connection. We need to investigate, it's possible it's only happening on the nominatim.openstreetmap.org server.

**Comment by lonvia** [comment]
This was a regression from the recent refactoring of SQL code. I've reindexed St. Cloud on both servers and it's back to MN where it belongs.

**Comment by iandees** [comment]
Thanks, @lonvia!
