### ISSUE TITLE
placex - missing admin_level 8 in parent_place_id chain after update

### ISSUE THREAD

**Issue by txtor** [openstreetmap/Nominatim#1710]
Hello. I have noticed a strange behavior in my nominatim instance and I don't know if there is an error or if I misunderstand something. I extract a list of cities and the suburbs / hamlets/ etc. that belong to them. Pretty often after I update nominatim some suburbs disappear from my list. The cause is that for a particular suburb if you follow the parent_place_id chain in placex you no longer meet the city.

For example Elspe N 267020140 
```
\set osm_type N
\set osm_id 267020140
with recursive t as (
select place_id, place_id t_place_id
from placex where osm_type=:'osm_type' and osm_id=:osm_id
union all
select x.parent_place_id, t.t_place_id
from t
inner join placex x on x.place_id=t.place_id
)
select x.class,x.type,x.osm_type,x.osm_id,x.admin_level,x.name->'name' nm
from t
inner join placex x on x.place_id=t.place_id;
  class   |      type      | osm_type |  osm_id   | admin_level |         nm
----------+----------------+----------+-----------+-------------+---------------------
 place    | village        | N        | 267020140 |          15 | Elspe
 boundary | administrative | R        |   1891506 |           6 | Kreis Olpe
 boundary | administrative | R        |     62761 |           4 | Nordrhein-Westfalen
```

In the parent_place_id chain for Elspe (admin_level 15), the municipality Lennestadt R 1891508 (admin_level 8) is missing. I wonder why... a few days ago Lennestadt was there.

Using nominatim v3.4.1, postgres 11.5

**Comment by txtor** [comment]
I would like to know:
1. why have some elements with admin_level > 8 at placex a parent_place_id with admin_level 6? (I expect admin_level 8, which is the smaller enclosing administrative boundary in the data)
2. why do some (a lot of) elements loose their parent with admin_level 8 and get a parent with admin_level 6, after a nominatim update, without an apparent reason?

**Comment by mtmail** [comment]
Do you use the stable http://nominatim.org/release-history/ release or the latest from github (if so which commit version, `git log -q | head -1`). Was the database initially imported with the same version? There've been a few changes in the logic lately and it helps to know exactly which version you run.

Since you're comfortable with SQL you can try `select place_force_update(place_id) from placex;` which will mark a place (and all children) to be reindexed. You can find the place_id by `select place_id from placex where osm_type='...' and osm_id=...;`. Then run `utils/update.php --index` on command-line to execute the reindex. It will only use one process and can run while Nominatim answers queries, it's not much different than the nightly updates. Sometimes

**Comment by txtor** [comment]
Thank you for your response.

I use nominatim v3.4.1 which I cloned from GitHub. The data for Europe was imported after installing it and since then daily updated.

```
git log -n 1
commit e4ecbef61ec21b4aff9fdaf6ba19d5c4ce80adbf
Author: [...]
Date:   Sat Dec 28 22:53:38 2019 +0100

    prepare for 3.4.1 release
```

I have forced the reindex as you indicated and after that the result is still the same.
```
 select place_force_update(place_id) from placex where place_id=126326795;
 ./update.php --index
 place_id  |  class   |      type      | osm_type |  osm_id   | admin_level |         nm
-----------+----------+----------------+----------+-----------+-------------+---------------------
 126326795 | place    | village        | N        | 267020140 |          15 | Elspe
 121768483 | boundary | administrative | R        |   1891506 |           6 | Kreis Olpe
 121612527 | boundary | administrative | R        |     62761 |           4 | Nordrhein-Westfalen
```

**Comment by lonvia** [comment]
I'd expect that the admin boundary 8 is not shown because place=village is currently ranked with address rank 16 which corresponds to admin level 8. The address should only include address parts that have a lower address rank.

So it would be actually the initial import which has the odd behaviour. The master branch indeed has a bug there (although that would appear in updates, too). I can't reproduce that on a 3.4.1 release. It correctly removes Lennestadt from the address on import. Is it possible that you have imported with a different version and only switched to 3.4.1 for updates?

**Comment by txtor** [comment]
I've double checked this on our repo -- This instance was initally installed on Jan 17 cloning the github nominatim tag v3.4.1. So it remains obscure, why this records where incorrect.

Thank you for the info. Now I am confused, because I don't know how to get it. When I have a place_id of a village or suburb,  how can I determine the place_id of the citiy it belongs to? Nominatim results include a nice administrative hierarchy of places up until the country. What tables / columns contain this hierarchy? If this is not too much OT, I would be grateful for any hints or pointers.

**Comment by lonvia** [comment]
The problem here is that the tagging in OSM is very vague and inconsistent. Sometimes a place=village is indeed a part of a place=town, sometimes the two are two distinct places next to each other. It requires quite a bit of guessing how to put that. Nominatim currently has a very simple algorithm that does not work equally well everywhere. This algorithm is currently under review, so hopefully the next version of Nominatim gets you much better results. If you are interested in a bit og background you can watch the [SOTM 2018 talk](https://2018.stateofthemap.org/2018/T094-Addressing_addresses/) about that.

Regarding the database, if you want to look up hierarchies, the best table for that is generally the `place_addressline` table, which lists all the elements of the hierarchy that Nominatim finds for a given entry in the placex table.

**Comment by txtor** [comment]
Great! Thank you very much for the infos and the pointers. 
Closing the issue.
