### ISSUE TITLE
doesn't reliably find exact matches on long streets

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/Nominatim#265]
The following case: Nominatim doesn't find exact matches for some housenumbers of a specific street without clicking on _"Search for more results"_, but does find others. Example: [Wienerstraße 68](http://nominatim.openstreetmap.org/search.php?q=wiener+stra%C3%9Fe%2C+68&viewbox=15.31%2C47.13%2C15.57%2C47.02) (not found) vs. [Wienerstraße 482](http://nominatim.openstreetmap.org/search.php?q=wiener+stra%C3%9Fe%2C+482&viewbox=15.31%2C47.13%2C15.57%2C47.02) (found).

After some [debugging](http://nominatim.openstreetmap.org/search?accept-language=en&addressdetails=1&bounded=1&format=json&q=Wiener+Stra%C3%9Fe+68&viewbox=15.587%2C47.152%2C15.313%2C46.971&debug=1), I think the reason is that the street has (much) more than 20 segments, and it is only a question of luck whether the searched housenumber is a child of one of the selected segments or not?

**Comment by lonvia** [comment]
It works reliably if you add the town to your search query. Without it is basically a won't-fix because there is too much data to go through. As you figured out correctly, the problem here is that house numbers are not part of the initial search index, so to look for that exact house number, Nominatim has to do a search through all the house numbers attached to all the `Wienerstr' in the world (feasible in that case but think about searching for 'Hauptstr 3').

**Comment by tyrasd** [comment]
I see. But I forgot to mention that I'm using a bbox-bound search query (a city plus some surroundings) and I don't know which town the housenumber actually belongs to before doing the search. Do you have any hints about how to improve my search results?

**Comment by lonvia** [comment]
I see, bounded searches are different indeed. It's possible to enable the house number-specific search from cf5ced6618c0c18eed4cafc2287e8c3813c9131f for those. But it needs looking into restricting the area for bounded searches.

**Comment by lonvia** [comment]
Nominatim does now filter the streets by attached house numbers, so this should work now. Please open a new issue if you find an example where it doesn't work.
