### ISSUE TITLE
Search for address in Karlsruhe city shows 10 results from Karlsruhe administrative region before results from the city for some addresses

### ISSUE THREAD

**Issue by florianjacob** [openstreetmap/Nominatim#329]
This is the original map issue, I was sent here as they said it's not an error in the mapping:
http://www.openstreetmap.org/note/460676#map=18/49.01134/8.39550&layers=N

A search for „Karlstraße 1, Karlsruhe“ (or any other way around) shows 10 results from Karlsruhe administrative region. The 11th result you see after clicking „More results“ is the entry actually searched for in Karlsruhe city.

This problem occurs for several other street numbers, too, but e.g. not for „Karlstraße 3, Karlsruhe“ - very strange. There seems to be no difference in the data of the two buildings.

**Comment by lonvia** [comment]
This is a known issue which has a few workaround in the code but not yet a really good solution.

What currently throws of Nominatim in Karlsruhe, is the name:ru on [this relation](http://www.openstreetmap.org/relation/22027). That's because Nominatim prefers results where the address parts have a full match. So, when there was only 'Regierungsbezirk Karlsruhe', he relation wouldn't fully match your query but now that the name:ru does result in a full match.

**Comment by florianjacob** [comment]
I understand, so the problem is that “Карлсруэ” gets normalised to “Karlsruhe“ for search, and then we have an exact match, because it's missing an equivalent of “Regierungsbezirk“ in front of it, like “администрати́вный о́круг” (administrative region).

Thanks for looking into this. :+1: .

**Comment by lonvia** [comment]
Nominatim currently computes a [secondary importance](https://github.com/openstreetmap/Nominatim/blob/master/lib/PlaceLookup.php#L135) to sort results with the same importance better. This address importance is only applied when reranking the result candidates. That is too late because at this point the correct result is already missing from the limited list of results. The address importance should be added to the overall importance of a place instead.

**Comment by lonvia** [comment]
While trying to fix this the hard way, I figured that the root cause for the given example is much simpler. The correct street is already in the result set. It is just the house number that is not found because of a misplaced limit. Fix now deployed on nominatim.openstreetmap.org.

Pushing address importance into search_name is still something worth considering but it can wait until actual issues come up where the current approach via exact matches does not work well.

**Comment by florianjacob** [comment]
Great stuff, I don't fully understand how you fixed this, but I'm very happy to see this has gone live already! :tada: :grinning: 

I might be able to provide a relevant example for what you previously intended to do (not sure, though):

Searches for "Karlsruhe, Karlstraße X" now works for the full range from 1 to 11 except  "Karlsruhe, Karlstraße 4" and "Karlsruhe, Karlstraße 8", which show a street in Heidelberg (part of Karlsruhe administrative region).

For the other way around, "Karlstraße X, Karlsruhe", "Karlstraße 1, Karlsruhe" shows the street in Karlsruhe, but the other numbers show same-named streets in seemingly random other cities in the Karlsruhe administrative region.

But in all the mentioned cases, after your fix, the "right" result is now one of the first few hits, or at least on the first page, so this is much less of an issue now. :+1:
