### ISSUE TITLE
Case-sensitivity in query: "LA" vs "la"

### ISSUE THREAD

**Issue by AnnaSkawinska** [openstreetmap/Nominatim#368]
Two searches differing only by case yield different results.:
1.
`curl --header "Accept-Language: en-US" 'http://nominatim.openstreetmap.org/search.p?format=json&q=la'
`
2.
`curl --header "Accept-Language: en-US" 'http://nominatim.openstreetmap.org/search.p?format=json&q=LA'
`
The former results in several matches for Louisiana, while the latter yields no results.

"LA" seems to be the only case I've found so far. Btw, both Google Maps and Photon find "Los Angeles" rather than "Louisiana" for the "la" query.

**Comment by mtmail** [comment]
It's one of the very very few cases where a single place gets special treatment inside Nominatim and I can point to the exact line

https://github.com/twain47/Nominatim/blob/master/lib/Geocode.php#L798

This replacement happens pre-query cleaning and I guess simply doesn't replace the LA when in uppercase. Yet.

It is interesting though that Los Angeles isn't returned instead because the OpenStreetMap data lists `LA` as `short_name` for http://www.openstreetmap.org/relation/207359

Photon uses an export of Nominatim-generated/processed index data. It skips that replacement because it happens at Nominatim search time.

Of course it's debatable if Los Angeles or Luisina is the better results. Inside a query like '<city>, LA' I personally argue it's the US state.

**Comment by lonvia** [comment]
There is another special treatment for 'la'. It's a stop word in some languages (article in French, Spanish, Italian etc.) and gets therefore deleted.

**Comment by askawinska-xsolve** [comment]
> It's a stop word in some languages (article in French, Spanish, Italian etc.) and gets therefore deleted.

As far as I've noticed, search result is language dependent, so this should not be a problem.

**Comment by AnnaSkawinska** [comment]
> It's a stop word in some languages (article in French, Spanish, Italian etc.) and gets therefore deleted.

As far as I've noticed, search result is language dependent, so this should not be a problem.

**Comment by lonvia** [comment]
The results are displayed in the language requested by the user. The treatment of the query input is language independent.

**Comment by lonvia** [comment]
Fixed in #905.
