### ISSUE TITLE
Finding street names of a given county

### ISSUE THREAD

**Issue by belious2015** [openstreetmap/Nominatim#377]
Is there a way to filter out the cities,street names, buildings and houses of a given (country,state,county).

thanks in advance

**Comment by mtmail** [comment]
There is no API call or script to get such bulk data from Nominatim directly. When you install Nominatim you can do database queries to extract such data. I've done that for customers for whole countries in the past.

Another option for you is to query a http://wiki.openstreetmap.org/wiki/Overpass_API instance (and/or setup your own),

Or the command-line tools `osmconvert` using raw downloaded data, see https://help.openstreetmap.org/questions/9816/the-best-way-to-extract-street-list

http://www.gisgraphy.com/download/download_data.htm, another geocoder using OpenStreetMap data, sells their indices and consulting services for extracting data sets.

Remember that after you extracted data to still attribute OpenStreetMap (http://www.openstreetmap.org/copyright)

**Comment by belious2015** [comment]
thank you,
i'm trying now to do some database query to extract all addresses situated within the boundaries of (country,state,county), but i'm not an expert in spatial database,
please an exemple of query, let's suppose we want to extract all addresses(street,buildings ...all) contained within the boundaries of (algerie, alger, El Mouradia)
any help please

**Comment by mtmail** [comment]
You need to freshen up your Postgres and PostGIS (http://postgis.net/documentation/) knowledge a bit.

1. search for the main geometry. Let's say Alger County. http://www.openstreetmap.org/relation/157062 It's important to find a type 'relation' because only that has outlines. In rare cases for cities you only see a 'node' (center point, e.g. http://www.openstreetmap.org/node/299617915) and then you'd have to calculate a radius around the center.

2. in the database you get the record like this: `select place_id, parent_place_id, name from placex where osm_type='R' and osm_id='157062';` You can see which columns exist with `\d placex`. `select *` won't be readable because the `geometry` column is very large. The `name` column is of type hstore (http://www.postgresql.org/docs/current/static/hstore.html), so get the primary name use `name->'name'`, to get the French name `name->'name:fr'`, for the arabic name `name->'name:ar'`.

3. Now you can search for anything inside Alger's geometry. `select place_id from placex where ST_within(centroid, (select geometry from placex where osm_type='R' and osm_id='157062'));`
http://postgis.net/docs/ST_Within.html

4. Each place it linked to a parent. You can generate a hierarchy (tree?) going from housenumber to street to city etc in a script. 

4b. alternatively you can look at the HTML content of `<your server>/nominatim/hierarchy.php?place_id=<place_id>` for each place. That's takes longer but saves you writing the hierarchy logic yourself.

4c. another alternative is look at the centroid of each place and run `<your server>/nominatim/reverse.php?format=json&lat=<lat>&lon=<lon>&addressdetails=1&namedetails=1`. To convert centroid into lon,lat in postgres use `ST_AsText()` (http://postgis.net/docs/ST_AsText.html, https://en.wikipedia.org/wiki/Well-known_text)

All together it's complex. Nominatim has the database tables to find places fast and exporting address lists is unusual.

**Comment by lonvia** [comment]
I've written an export script many moons ago to kind of do what you want: https://github.com/lonvia/Nominatim/blob/export-script/utils/export.php It's entirely unsupported and I don't know if it still works with the current code but at least it might give you an idea how to do it.

**Comment by lonvia** [comment]
If somebody wants to update and polish that script, it would make a nice addition to the utils collection.
