### ISSUE TITLE
don't import historic roads

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/Nominatim#491]
Half proposal, half question, I can provide a pull request.

Nominatim finds old roman roads http://www.openstreetmap.org/way/400160077

Based on the documentation `historic=roman_road` can describe a current existing road but also no longer existing roads. One has to check if other tags like `highway` are set http://wiki.openstreetmap.org/wiki/Proposed_features/roman_road

Taginfo reports 2500 ways, 20 relations. http://taginfo.openstreetmap.org/tags/historic=roman_road

Other `historic` keys should be fine. Usually they're nodes or represent small areas. Roads on the other hand are relatively large and confuse reverse search: a result gets returned which no longer exists. In fact all the common map styles don't render the road.

**Comment by lonvia** [comment]
I don't think we should exclude these kind of objects completely from the database. It's still okay to do a forward search for them but I see your point that they cause havoc with reverse geocoding. However, excluding specifically roman roads doesn't scale either. Tomorrow it's some other obscure feature that gets in the way (thinking man_made=* which we had to exclude last time because of obscure power lines). How about excluding all LineString features at address rank 30?

**Comment by lonvia** [comment]
Should be fixed in 16794a8.
