### ISSUE TITLE
Import full Ordnance Survey CodePoint database for searching

### ISSUE THREAD

**Issue by gerv** [openstreetmap/Nominatim#541]
Many postcodes in the UK still don't produce a hit on Nominatim. Examples:
http://www.openstreetmap.org/search?query=LE11%201PN
http://www.openstreetmap.org/search?query=EN2%208LA

Either the CodePoint Open full postcode database hasn't been imported, or there's something wrong with the search. Discussion on the talk-gb mailing list concluded that the problem of not being able to find postcodes is best fixed in Nominatim - see this message and following:
https://lists.openstreetmap.org/pipermail/talk-gb/2016-September/019234.html

90% of the map searches I do are postcodes, and right now I have to use Google Maps for certainty. Can this long-standing OSM sadness be resolved? :-)

Gerv

**Comment by lonvia** [comment]
Nominatim contains a copy of the CodePoint database but explicit postcode search via this database has never worked because nobody has ever implemented it. The CodePoint DB is only used to pinpoint the location of a search. Note that postcode search via the OSM database is limited as well because postcode centroids are only ever updated when the database is reimported (last one was only last week as it happend).

So here is the full todo list for getting this issue solved (ordered by difficulty, easiest first):

 * implement reverse lookup for coordinate search based on CodePoint coordinates when a UK postcode is detected
 * implement #403 
 * solve [normalization issue](https://trac.openstreetmap.org/ticket/4910)

From my side, #403 is higher on the TODO list because it solves postcode issues for the entire world. But if somebody from the UK community wants to tackle the CodePoint lookup that would be welcome.

Also related: #221

**Comment by lonvia** [comment]
Fixed with #782.
