### ISSUE TITLE
results not found until completing second word

### ISSUE THREAD

**Issue by mbfbsae90** [openstreetmap/Nominatim#694]
From the http://nominatim.openstreetmap.org/ page's search bar.

If I enter: κυδωνίων, α   Things are found.
If I enter: κυδωνίων, αι  Nothing is found
If I continue adding characters nothing is found until the end of the second word.
if I enter: κυδωνίων, αιγάλεω  1 thing is found.

Why is this happening? This also gives the same results using the API...

Thx,
Mark

**Comment by mtmail** [comment]
Nominatim actually can't search part of words. Or spell-checking or type-ahead (search while you type in a searchbox). "α" gets ignored in the query (too short), "αι" gets treated as a full word (not found) until the word is complete.

These limitations are as old as Nominatim itself (5+ years). We're at version 2.6 and none of those features will be ready for version 3 even. Instead of pointing to to 5 year old github issues I'll point you to http://photon.komoot.de/. Photon uses OpenStreetMap data (actually a data dump from Nominatim) and can do what you're looking for. Sadly it doesn't seem to find/know that street.
