### ISSUE TITLE
Cannot get Dublin City relation

### ISSUE THREAD

**Issue by milovanderlinden** [openstreetmap/Nominatim#699]
I can somehow not get the Dublin City relation. The query always ends up on the node
http://nominatim.openstreetmap.org/search.php?q=dublin&polygon_geojson=1&viewbox=&featuretype=settlement

If I look at the details, I can see that the relation comes second. How can I get this with a 
http://nominatim.openstreetmap.org/details.php?place_id=48468532

Should the tags for node 3473474851 be removed so that nominatim will find the relation instead of the node? Or will this break other things?

**Comment by lonvia** [comment]
Add the node to the relation with role "label". Nominatim has trouble figuring out that the two belong together because admin_level and place type don't match as expected. Once the two are connected, you will get the relation.

If you want to get the two always separately, you need to add 'dedupe=0' as a parameter.

**Comment by milovanderlinden** [comment]
Ok, thank you. I indeed added the node to the relation as can be seen here http://www.openstreetmap.org/relation/1109531 closing this issue. Thanks for helping me @lonvia!
