### ISSUE TITLE
HTML error output when asking for json format

### ISSUE THREAD

**Issue by ahoka** [openstreetmap/Nominatim#701]
When I issue the following query to force an error:

  search.php?format=json&viewbox=1234

I get an HTML response describing an error instead of the expected JSON. This makes consuming the error output hard. It would be better if the API caller got all possible errors in the requested format with a fixed schema.

**Comment by lonvia** [comment]
That should be possible and fairly easy to do. It just needs minor changes in the error handling functions to tell them about the selected output format.

Any takers for this issue?

**Comment by rumpletweezer** [comment]
I would like very much to take on this issue - however, I have never contributed to an open source project before and so wonder if this is the best place to start. Please advise - and please be blunt: I am keen to be useful to the project.
Secondly - I presume it would make sense to allow error reports in all possible formats at the same time as adding json?

**Comment by lonvia** [comment]
Please go ahead. This is a nice issue to start because it is only about the PHP frontend and does not yet touch the database. The error handling functions are in `lib/init-website.php`. It would be nice if html, json and xml all work correctly. Note that for json output there can be format=json and format=jsonv2 parameters.

**Comment by mtmail** [comment]
I started a while back with the templates. Feel free to copy them from https://github.com/openstreetmap/Nominatim/compare/master...mtmail:workinprogress-json-errors-701?expand=1

The easiest way to setup a development environment is probably the Ubuntu Vagrant virtual machine. See `Vagrant.md`. I usually import a small country like Monaco or Luxembourg.

The build directory can be confusing. For example there's a `website` directory in `Nominatim` (the directory one checks out from git), and the cmake&&make build progress from the installation creates another in the `build` directory. The website displays the one in the `build` directory, so I copy the files regularly. During development you don't have to restart the webserver (no caching).

**Comment by rumpletweezer** [comment]
Thanks so much, both!  I will get stuck in.

**Comment by rumpletweezer** [comment]
I have made most of the required changes - all seems to be well. Thanks again for the templates, @mtmail ! I want to do some more testing (and phpcb-ing!) before submitting a pull request. 
The only place I am struggling is the userError in the 'lookup' function in 'Geocode.php' - not clear how to determine the format requested. I am no doubt missing something obvious.
I assume the statusErrors (in status.php) fall outside of the remit of this issue?

**Comment by lonvia** [comment]
Getting the format is tricky, indeed. I can't even recommend parsing _GET again because the default format depends on the API endpoint being used. I fear that some kind of global variable is needed which is set up in the website/*php scritps. @mtmail, do you have a better idea?

status.php is a separate thing, yes. It really only ever returns a text file.

**Comment by lonvia** [comment]
Regarding tests: there are already a couple of tests for user errors in `test/bdd/api`. Grep for 'HTTP 400 is returned'. If you feel like extending these tests, so that they parse the structured json or xml query and actually check that the right error message is returned, that would be awesome.

**Comment by rumpletweezer** [comment]
Good idea about tests! I will gladly (try to) extend the tests.
I guess we would prefer to avoid another global. Is there a reason why we do not have a 'base class' which holds $oParams? (and perhaps $oGeocode)? Then if search.php, reverse.php, etc. extended the base class, they could access using $this->oParams, and avoid some code reuse in various places as well. 
But is there no doubt a much simpler solution that that in the case I mentioned earlier. I will have another look.

**Comment by mtmail** [comment]
The website/*.php files set a response header, e.g. `header('content-type: application/json; charset=UTF-8');`. I wonder if we set that early enough, if then the error logic could read that value and select the appropriate output format. (yes, sounds like a hack).

**Comment by rumpletweezer** [comment]
I have added an argument to Geocode's lookup function so that
`public function lookup($format = 'html')` and have passed the format in all the places I can find the function being called. Hope that is ok.

**Comment by lonvia** [comment]
The base class idea sounds ok to me. However, that means that you have to move quite a bit of code around. And if you do that, I wonder if it isn't worth going the whole way and replace all this hacky userError() stuff with proper exception handling (see #947). It would also be perfectly fine to do all that in stages. Start with what you have and get that PR done and then clean up the format parameter stuff.

@mtmail Parsing the header seems even more hacky than a global variable..

**Comment by lonvia** [comment]
The parameter is okay, too, as an intermediate solution but in the long run I'd like to keep the format out of the Geocode class because it really shouldn't care about that.

**Comment by rumpletweezer** [comment]
I have been unable to get 'behave' to work on my setup, after a couple of hours. (I had never come across it before) I am sure it is down to me, but that doesn't change the fact I can't run the tests - or add new ones.

**Comment by lonvia** [comment]
That's a shame. If you care to join the [#osm-nominatim channel on IRC](https://wiki.openstreetmap.org/wiki/IRC) we can try to get it sorted out. Or you can open a new issue here about the behave troubles.

**Comment by rumpletweezer** [comment]
I think my changes to the code are ok - but I am having a problem with understanding why my behave tests are not performing as I expect them to. I have added a new test to check if an error message matches what is expected for each format. The json and jsonv2 test pass, but the html test returns an internal server error instead of the correct one. The xml returns the correct error, but the test does not detect it as such. I suspect my set up for the html problem (my api tests return several 500 errors instead of 400 or 200), and my poor python and behave skills for the the xml problem. To look at the xml problem first, my new step for all formats is as follows: 
`@then(u'the result page will include (?P<error>.*).')
   def error_check(context,error):
   if not error in getattr(context.response,'page'):
   assert not error, "Incorrect error displayed. Expected page to contain \"%s\        " but got %s" % (error, vars(context.response))` 
with the behave part looking like this:
`Scenario Outline: Missing lon parameter error
              When sending <format> reverse coordinates 52.52,
              Then the result page will include <text>
      
          Examples:
           | format | text |
           | json | Need coordinates or OSM object to lookup. |
           | jsonv2 | Need coordinates or OSM object to lookup. |
           | html | Need coordinates or OSM object to lookup. |
           | xml | Need coordinates or OSM object to lookup. |`

I am sure I am missing something obvious - any advice would be gratefully received.

**Comment by lonvia** [comment]
Do you mind opening a PR with what you have? It is easier to comment on the code directly.

Regarding the 500 errors: you should run the tests against master first and verify that everything passes there.

**Comment by rumpletweezer** [comment]
Sure thing - have now done so: https://github.com/openstreetmap/Nominatim/pull/972

**Comment by lonvia** [comment]
Fixed in #1181.
