### ISSUE TITLE
No result instead of approximate result for a known address

### ISSUE THREAD

**Issue by jmarca** [openstreetmap/Nominatim#706]
Hi.

I was testing out the nominatim service and put in a house I know of in Burbank CA:

430 E. Fairmount Rd., Burbank, CA, 91501

I got no result back.

I put in 482 E. Fairmount Rd., Burbank, CA 91501 and got a "valid result", even though there is no such address, and even though that result points at the house that is actually numbered 430.

<http://nominatim.openstreetmap.org/search.php?q=482+E.+Fairmount+Rd.%2C+Burbank%2C+CA+91501&polygon_geojson=1&viewbox=>

Last week, hoping to fix these results, I inserted the house number at the end of the block, 432 on the right side, and 437 on the left.  I was hoping to convince the nominatim engine to interpolate the house addresses from 400 to 432.  No joy.  A query for 432 works properly:

<http://nominatim.openstreetmap.org/search.php?q=432+E.+Fairmount+Rd.%2C+Burbank%2C+CA+91501&polygon_geojson=1&viewbox=>

but a query for 430 fails

<http://nominatim.openstreetmap.org/search.php?q=430+E.+Fairmount+Rd.%2C+Burbank%2C+CA+91501&polygon_geojson=1&viewbox=>

What I would expect would be an approximate match.  Even though the numbering interpolation is incorrect for this part of the city of Burbank, I would expect nominatim would at least pick an approximate place maybe 1/3 of the way up the block, instead of no result.  Second, I would expect that given that nominatim knows how to find the house number 432, it should deduce that the remaining houses on the block run from 400 to 432 and interpolate accordingly.

I hope this report is helpful.

**Comment by lonvia** [comment]
Nominatim doesn't do interpolation between simple address points and probably never will. You can use [adress interpolations](http://wiki.openstreetmap.org/wiki/Addresses#Using_interpolation) to express this kind of approximation in OSM data and Nominatim will be able to handle it.

That said, the address you give should be in the suplementary Tiger data we use. And even failing that you should get the street as a result if Nominatim cannot find the exact address. So there is definitely a bug here. It looks like the postcode is posing problems because this works fine:
http://nominatim.openstreetmap.org/search.php?q=430+E.+Fairmount+Rd.%2C+Burbank%2C+ca&polygon_geojson=1&viewbox=

**Comment by jmarca** [comment]
Yeah I wasn't trying to ask for a new feature (interpolation) so much as observing that to me it *appeared* that nominatim was interpolating addresses at some stage (perhaps interpolated at setup time?) and then apparently refusing to entertain any addresses outside of those numbers.  

Again this is because there is no such house as 482 E Fairmount. AND there is in fact a house at 430 E Fairmount that wasn't showing up in the query. 

I couldn't find where this might be happening in the code, or even how it was guessing that the addresses on that street run from 400 to 500, so I can't suggest a code fix, nor can I suggest a generic way to provide hints that addresses in X city should increment by twos, etc etc. 

*BUT* as you observed, the URL without the post code works okay. Just tested it and apparently it also works okay if there is a comma between CA and 91501. So perhaps the bug is classic case of user error; is in how I entered the address?

James

**Comment by lonvia** [comment]
Those interpolations you found come from the Tiger data (US government census data which contains an exhaustive list of housenumber interpolations). Nominatim uses those as fallback in the US when the house number you ask for cannot be found in the OSM data. The data can be patchy where Tiger data and OSM street data don't match up. That's why you sometimes see interpolations and sometimes you don't.

The bad result is not a user error, your input is fine (although the more commas the better). Nominatim's heuristics in how it interprets your input is flawed. Simply said, it spends too much energy looking for a place called '430' and not enough energy looking for places with housenumber '430'. That can be changed but I need to figure out first what other side-effects such a change might have.

**Comment by lonvia** [comment]
The data on the server might have changed but now it is a postcode problem. The street in question has 91504 as postcode in our data. That is most likely because OpenStreetMap does not yet have enough data. Ignoring unknown postcodes is a known issue, see #537. So closing here.

**Comment by jmarca** [comment]
Hmm!  Given that I grew up on that street, I'm pretty sure the post code is correct!  It switches one block over. I'll see about correcting OSM.   

Thanks for looking into this.
