### ISSUE TITLE
Search for Marktplatz 1

### ISSUE THREAD

**Issue by OSMmapper** [openstreetmap/Nominatim#738]
If i search for Adresses wirth the Street "Marktplatz 1" (Marketplace 1) there is no hit
and the map jumps somewhere.

http://www.openstreetmap.org/search?query=reutlingen marktplatz 1
http://www.openstreetmap.org/way/50586240

http://www.openstreetmap.org/search?query=leinfelden-echterdingen marktplatz 1
http://www.openstreetmap.org/way/72900024

http://www.openstreetmap.org/search?query=stuttgart marktplatz 1
http://www.openstreetmap.org/node/3456076920

If i search for another housenumber i will get correct results...

**Comment by lonvia** [comment]
This is another example of #216.

What happens is that "marktplatz 1" matches against the special phrase "markplatz in" because 1 == I (the roman numeral) == i. (because we don't care about case or punctuation) == in. And as Nominatim doesn't care about order it interprets the query as "find me all amentiy=marketplace in reutlingen".

Closing as duplicate here.
