### ISSUE TITLE
No results when adding postal code to search query FR

### ISSUE THREAD

**Issue by WesSylvain** [openstreetmap/Nominatim#750]
Hello,

Problem **postcode** in France (50% results with postalcode...)

Street : 7 RUE DES BRUYERES
**Postalcode: 69330**
City : pusignan, 
Country : france

[Result](http://nominatim.openstreetmap.org/search.php?street=7+RUE+DES+BRUYERES&country=france&city=pusignan) vs [No result](http://nominatim.openstreetmap.org/search.php?street=7+RUE+DES+BRUYERES&postalcode=69330&country=france&city=pusignan)

other : 

Street : 6 AVENUE DE LA GARE
**Postalcode: 60580**
City :  COYE-LA-FORET,
Country : france

[Result](http://nominatim.openstreetmap.org/search.php?q=6+AVENUE+DE+LA+GARE+COYE-LA-FORET&polygon_geojson=1) / [No result](http://nominatim.openstreetmap.org/search.php?q=6+AVENUE+DE+LA+GARE+COYE-LA-FORET+60580&polygon_geojson=1)  

I hope somebody can help me out :)
Thank you

**Comment by lonvia** [comment]
Due to #746 a lot of postcodes are currently missing from the search index (even though they may appear in the displayed name) on nominatim.openstreetmap.org. They will gradually reappear when data is changed but that may take a while. I'll see if I can speed up the process.

**Comment by WesSylvain** [comment]
Thank you

**Comment by lonvia** [comment]
The US and France are now recalculated for a large part. I'll do other countries on request.

Your first example still does not work because the postcode from the county (which you see appear in the result) is not added to the search index of the road and therefore not searchable. This is a known problem and on already pretty high on the list of things to improve.

**Comment by ka4ok85** [comment]
What does "large part" mean? Do you have any plans to recalculate 100% US zip codes? Could you please recalculate Washington State?

I am still struggling with Seattle area:
http://nominatim.openstreetmap.org/reverse?format=json&addressdetails=1&lat=47.612625&lon=-122.34128
http://nominatim.openstreetmap.org/reverse?format=json&addressdetails=1&lat=47.592506&lon=-122.311966

**Comment by lonvia** [comment]
All streets in the US are freshly calculated. If you encounter streets without postcodes, then the current algorithm for calculating postcode is not sufficient to resolve one. There are a number of known issues. Most notably there are problems because Nominatim only works with point information for postcodes.
