### ISSUE TITLE
Filter out "Admin level 15" on reverse request

### ISSUE THREAD

**Issue by Megachip** [openstreetmap/Nominatim#766]
It's really confusing that some `admin level 15` are sprinkeled between lower levels, especially there nodes.

Example:
http://nominatim.openstreetmap.org/details.php?place_id=23136105

```xml
-<addressparts>
    <suburb>Bahnhofsviertel</suburb>
    <city_district>Bahnhofsviertel</city_district>
    <city>Frankfurt</city>
    <county>Frankfurt</county>
    <state_district>Regierungsbezirk Darmstadt</state_district>
    <state>Hesse</state>
    <postcode>60329</postcode>
    <country>Germany</country>
    <country_code>de</country_code>
</addressparts>
```
So in that case I think city_district = suburb and county = city?
Why county is set even there is noch level 7 in chain? Same for suburb...

**Comment by lonvia** [comment]
`admin_level = 15` in the details view just means that the OSM object does not have an explicit admin_level tag, so can be pretty much ignored. It's possibly not the best information to show there. We should probably display the address rank instead.

The boundaries and nodes with the same name actually belong together and should be merged for the purpose of creating the address. The problem here is that Nominatim makes different assumptions about how boundaries with admin_level and places with their descriptive names (city, suburb etc.) belong together. It's pretty hard to get that right automatically. So the best here is to help Nominatim and add the nodes to the boundary relation with the role 'label', i.e. in the case above node 27418664 should be added to relation 62400 and node 2274148300 to relation 4209935. Once you do that, the duplicates will go away.

**Comment by Megachip** [comment]
@lovia so same Thing for http://www.openstreetmap.org/node/20830918 and http://www.openstreetmap.org/relation/62594?

But it is added as `admin_centre`. Should it added a as a second relation with `Label`?
