### ISSUE TITLE
Nominatim update via pyosmium error column "none" does not exist.

### ISSUE THREAD

**Issue by gsv91** [openstreetmap/Nominatim#784]
I have:
1) 2GB RAM size, 1 core 3GHz, 100GB disk space
2) VM with CentOS 7.3
3) Postgresql 9.6, Postgis 2.3.2 r15302
4) Nominatim version 3.0.1

I have successfully installed nominatim ver 3.0.1 on centOs 7.3. Imported my region pbf from geofabrik. Set CONST_Pyosmium_Binary, CONST_Replication_Url, CONST_Replication_Update_Interval and CONST_Replication_Recheck_Interval. When I am trying to update manually via command "./utils/update.php --init-updates" I am getting error:

PHP Warning: pg_query(): Query failed: ERROR: column "none" does not exist LINE 1: ...quence_id, indexed) VALUES('2017-08-21T20:34:32Z' ,None, true... in <nominatim home="">/Nominatim/build/utils/update.php on line 87 ERROR: Could not enter sequence into database. Could not enter sequence into database.

Is it bug or something wrong during my installation? Nominatim search working as expected.

**Comment by lonvia** [comment]
Two more questions: where did you install pyosmium from and what version do you use? What is the content of the CONST_* variables you mention?

**Comment by gsv91** [comment]
I installed it via "pip install --user osmium" for user nominatim with home directory "/home/srv/nominatim". So it located in "/home/srv/nominatim/.local/bin/*".
In settings/local.php I have:

```
@define('CONST_Pyosmium_Binary', '/home/srv/nominatim/.local/bin/pyousmium-get-changes');
@define('CONST_Replication_Url', 'http://download.geofabrik.de/russia/central-fed-district-latest.osm.pbf');
@define('CONST_Replication_Update_Interval', '86400');
@define('CONST_Replication_Recheck_Interval', '900');
```

**Comment by lonvia** [comment]
Ok, so your replication URL is wrong. This should point to the directory, where diffs can be found. For your extract that would be `http://download.geofabrik.de/russia/central-fed-district-updates/`.

There is still a bug here as it should tell you simply that there are no updates instead of giving you the strange message about the none column.

**Comment by lonvia** [comment]
I have added an additional sanity check in `utils.php --init-updates` that the configured URL actually points to a replication repository. I have also pushed a fix to pyosmium, so that the pyosmium-get-changes tool now correctly reports an error, when it cannot find any point where to start the updates.
