### ISSUE TITLE
Feature request: Nearby Searching for non special words

### ISSUE THREAD

**Issue by hactar** [openstreetmap/Nominatim#796]
I'm exploring nominatim as a replacement for the google places api that I use in some projects. One thing that I frequently need is to find the closest "keyword" near "lat, long". As an example, finding the closest starbucks to 48.20887,16.36620: 

There appear to be to ways of doing this at the moment:
1) query for "restaurant near [lat,long]" - this is great, however it only works for the defined special words. If I wanted to find "starbucks near [lat,long]" I get no results because starbucks isn't one of the magic words.
2) query for "starbucks", set a bounding box and set bounding=1 - this however only finds the starbucks if it is within the bounding box, if I pick a bounding box that is too small I get no results. Trying to guess the right bounding box can be difficult.

It would be great if option 1 would work for non special words too.

**Comment by lonvia** [comment]
Simply "Starbucks lat,lon" should work.

**Comment by hactar** [comment]
Nice, thank you! That does work well. Didn't see that an option on http://wiki.openstreetmap.org/wiki/Nominatim

Tiny comment: I would have expected the results to be sorted by distance to the point (assuming they have the same importance), however if you look at http://nominatim.openstreetmap.org/search.php?q=starbucks%2048.207661,16.3670147&polygon_geojson=1&accept-language=de&format=json , the coordinate is at "place_id": "20006522", yet multiple other nearby starbucks are listed before that closest one. Its nothing major, I can do the sorting on the client side, but it be a nice to have if the server did the sorting.

**Comment by lonvia** [comment]
The results do now get ordered by distance but only for searches that contain a coordinate. Something like 'cafe near Michaelerplatz, Wien' still gets the standard search order.

**Comment by nayrban** [comment]
hello, first of all I am a fan of Nominatim, it help me a lot with a recent project, so thank you guys for your work.
Quick question about the same topic, if I include a `"lat,lon"` in my query for example this is returning one result `https://nominatim.openstreetmap.org/search.php?q=honda+la%20Costa%20Rica%209.900185,-83.676235&format=json`, but I expect more than one
so my question is how do Nominatim calculate the near places around these coordinates, it has a limit to do the search in terms of distance?, I am not sure if I am not getting the way this works with `lat/lon`, it limits the results?. For example if I remove the coordinates then I start receiving more results, obviously because then is searching just for coincidence with the reference, but I want to apply also lat/lon because of the sorting

**Comment by mtmail** [comment]
@nayrban Use help.openstreetmap.org for quick questions. This issue is unrelated and has been closed for months.
