### ISSUE TITLE
Reverse Location is returning wrong country

### ISSUE THREAD

**Issue by Infinity86** [openstreetmap/Nominatim#844]
Actual result
Reverse geocode returns country PL for lat: 49.711950, lon: 18.641700.
in response I've receive 
{"place_id":"177726095","licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright","osm_type":"relation","osm_id":"49715","lat":"52.0977181","lon":"19.0258159","display_name":"Polska","address":{"country":"Polska","country_code":"pl"},"boundingbox":["49.0020468","55.0336963","14.1229707","24.145783"]}
which has totally different lat and lon (exactly center of Poland).

Expected result
https://nominatim.openstreetmap.org/search.php?q=49.711950%2C+18.641700&polygon_geojson=1&viewbox=
returns: 24, Osówki, okres Frýdek-Místek, kraj morawsko-śląski, Moravia-Silesia, 73961, Czechy (House)

This case it is our unit test of Nominatim that was working for more than a year, first failure we received at 2017-10-30 09:25:09.

**Comment by Infinity86** [comment]
Now I know what is giving wrong return.
Try this one: 
http://nominatim.openstreetmap.org/reverse.php?lat=49.711950&lon=18.641700&zoom=0
zoom = 0 (country level) is returning wrong country.

**Comment by mtmail** [comment]
Just adding context: the search point is 20m away from the border (north: Poland, south: CZ). Still an error but maybe more understandable.

http://nominatim.openstreetmap.org/reverse.php?lat=49.711950&lon=18.641700&format=html

![image](https://user-images.githubusercontent.com/3727288/32355688-82a27842-c030-11e7-9222-e239e0ce8daa.png)

**Comment by lonvia** [comment]
I would consider that a data error. The closest object that Nominatim can find is [this street](http://www.openstreetmap.org/way/49771214) which occaisonally crosses into Poland while following the border. It also to happens to cross at the centroid of the street, so that the street as a whole is put into Poland. Given that [Nominatim gets you the address of the closest object](http://nominatim.org/faq#point-outside-address) the result is for the country is Poland.

The street should really be cut into segments and/or the location of the boundary relative to the street fixed.
