### ISSUE TITLE
Search by phone number

### ISSUE THREAD

**Issue by woodpeck** [openstreetmap/Nominatim#861]
The following e-mail was received by the OSMF board. I am relaying it here for your consideration (without judging the merit of the suggestion in any way), and will respond to the person who made this suggestion including a pointer to this issue.

----

Hello

An Idea To Find Better Places

OSM Maps Developers Group

This is an idea to make a better and easier "Search" in OSM Maps for the people.

In OSM maps, search facility is difficult because there is an opened source to name the streets and the alleys and naming the streets depends on the various tastes as well, the large centers (Plazas) are named by a lots of people using English or local words .Most of the time, the location exists, but the search is failed.

But, if we add another field in “Search” parameters sheet as Search by phone no / cell phone, the user can find the location immediately using a phone number that is unique in all over the word, without entering or knowing the name of the streets, the alleys and the locations.

To do this, the user can assign a phone number on the map as the main address for his location or company to make an easier and faster search based on the same phone number.

Each phone number on the map is actually like a private and truncated ID of any company or location that makes the searching process very quick and without error.

Thank you for your attention and good luck.

**Comment by lonvia** [comment]
This is more of a mapping issue than a search issue, i.e. the data needs to be available in OSM. So you need to take the idea to the tagging mailing list. That said, I'm not very keen on adding phone numbers to the search because searching for numbers needs to be handled slightly different than searching for names. So we'd need to special case that.

Closing for now. If at some point there is a well-accepted tagging schema for something like this, we can revisit the inclusion in the search engine.
