### ISSUE TITLE
API with OSM identifiers

### ISSUE THREAD

**Issue by D063520** [openstreetmap/Nominatim#863]
Hello, 

thank you for providing this cool tool! I checked the documentation of the APIs and I couldn't find a way to get, given the coordinates, the detailed address *including* the OSM identifiers like here:

http://nominatim.openstreetmap.org/details.php?place_id=89331573

Is there a way to get the OSM identifiers:

relation 946245
relation 115135
and so on

starting from the geocoordinates 59.64086895,57.0242006090432?

Thank you
D063520

**Comment by mtmail** [comment]
There's no API endpoint that will return details (other than name) of the parent hierarchy of a place. 

If you're running your own instance of Nominatim it's possible to change the output template to add that information. Let me know and I can post the filenames and subroutines.

http://nominatim.openstreetmap.org/reverse.php?format=json&lat=59.64086895&lon=57.0242006090432

**Comment by D063520** [comment]
Hi,

yes, it would be really helpful if you could sketch, which parts I have to change to get the corresponding information.

Thank you
D063520

**Comment by mtmail** [comment]
In `sql/functions.sql` there's a PGSQL function `get_addressdata` which returns a list of `addressline` items. Similar to a SQL subquery or temporary table. `addressline` is defined as

```SQL
create type addressline as (
  place_id BIGINT,
  osm_type CHAR(1),
  osm_id BIGINT,
  name HSTORE,
  class TEXT,
  type TEXT,
  admin_level INTEGER,
  fromarea BOOLEAN,  
  isaddress BOOLEAN,  
  rank_address INTEGER,
  distance FLOAT
);
```

In `lib/PlaceLookup.php` there's a function `getAddressNames` which calls that PGSQL and converts the `addressitem`s to a PHP array `$aAddressLines`. Then each address line looped in a foreach and added to `$aAddress`.

In `template/address-jsonv2.php` (similar in `json` and `xml` equivalents) `$aPlace['aAddress']` gets added to the output.

So for example when calling http://nominatim.openstreetmap.org/reverse.php?format=json&lat=59.64086895&lon=57.0242006090432
the `$aAddress` (in `PlaceLookup.php`) and `$aPlace['aAddress']` (template files) contains
```php
[
  "administrative" => "Попова-Останина",
  "road" => "Тихая улица",
  "city" => "Половодовское сельское поселение",
  "county" => "Solikamsky District",
  "state" => "Perm Krai",
  "postcode" => "618513",
  "country" => "Russia",
  "country_code" => "ru"
]
```

To add `osm_type` and `osm_id` have a look at the line
```php
  $aAddress[$sTypeLabel] = $aLine['localname'] ? $aLine['localname'] : $aLine['housenumber'];
```
in `PlaceLookup.php`. Instead of assigning a string to the key you can assign an array
```php
  $aAddress[$sTypeLabel] = array(
    "name" => ($aLine['localname'] ? $aLine['localname'] : $aLine['housenumber']),
    "osm_type" => $aLine['osm_type'],
    "osm_id" => $aLine['osm_id']
  );
```

You can also add the `admin_level`, `rank_address`, `distance` like you see in the HTML table http://nominatim.openstreetmap.org/details.php?place_id=89331573

**Comment by D063520** [comment]
Hi, I will try to put it up. I close the issues for now, if I need more help I will open it again.
Thank you very much!!!!
D063520

**Comment by D063520** [comment]
Hi it worked!!!!

Your description was perfect! One last questions. At this page http://nominatim.openstreetmap.org/details.php?place_id=89331573 under address there is something like place:state, boundary:administrative, place:country. Is there somewhere a full list of possible types? Where are these types coming from?

**Comment by lonvia** [comment]
Please one ticket per topic. For the address part the types are essentially the combinations of class and type mentioned in https://github.com/openstreetmap/Nominatim/blob/master/sql/functions.sql#L828 ff. Objects of rank 30 can have arbitrary types.

**Comment by D063520** [comment]
thank you
