### ISSUE TITLE
Import won't run in VM with flatnodes enabled

### ISSUE THREAD

**Issue by chrissfoot** [openstreetmap/Nominatim#877]
I cannot get a Europe wide import to run with flatnodes enabled. I get the following output when I try

```
osm2pgsql version 0.93.0-dev (64 bit id space)

Using projection SRS 4326 (Latlong)
NOTICE:  table "place" does not exist, skipping
Allocating memory for sparse node cache
Node-cache: cache=10000MB, maxblocks=160000*65536, allocation method=9
Mid: loading persistent node cache from /Nominatim/Nominatim3/flatnodes.bin
Mid: pgsql, cache=10000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /Nominatim/europe-latest.osm.pbf
Using PBF parser.
Processing: Node(9690k 646.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
Processing: Node(10820k 491.8k/s) Way(0k 0.00k/s) Relation(0 0.00/s)node cache: stored: 11128332(100.00%), storage efficiency: 50.00% (dense blocks: 0, sparse nodes: 11128332), hit rate: -nan%
Osm2pgsql failed due to ERROR: mmap (remap) failed: Cannot allocate memory
ERROR: Error executing external command: /Nominatim/Nominatim3/build/osm2pgsql/osm2pgsql --flat-nodes /Nominatim/Nominatim3/flatnodes.bin -lsc -O gazetteer --hstore --number-processes 1 -C 10000 -P 5432 -d nominatim /Nominatim/europe-late
st.osm.pbf
Error executing external command: /Nominatim/Nominatim3/build/osm2pgsql/osm2pgsql --flat-nodes /Nominatim/Nominatim3/flatnodes.bin -lsc -O gazetteer --hstore --number-processes 1 -C 10000 -P 5432 -d nominatim /Nominatim/europe-latest.osm.
pbf
```

I have plenty of disk space (over 900 gb) and 8gb memory free when the import fails (16gb in total).

The command i'm running is:  ./build/utils/setup.php --osm-file ../europe-latest.osm.pbf --all --osm2pgsql-cache 10000 --threads 4 2>&1 | tee setup.log

It does create the flatnodes.bin file though it seems to vary in size from 500mb to 1gb depending on how quickly it fails. Without the flatnodes file definition in local.php it seems to carry on importing. 

I've tried it with a small (4mb) import too and it still fails in the same way

Any ideas what i'm doing wrong?

**Comment by lonvia** [comment]
Try reducing the memory used for --osm2pgsql-cache. Also make sure that overcommitting memory is allowed: `cat /proc/sys/vm/overcommit_memory` should print 0 or 1.

**Comment by chrissfoot** [comment]
The server has 11gb of free memory and free shows me that there is plenty of it available when it fails, nevertheless I have tried --osm2pgsql-cache with 6000 and 2000 with the same result. overcommit_memory returns 1 but I have tried it at 0 and 2 as well with the same result.

**Comment by lonvia** [comment]
Please add the following information to your issue:

*    Operating system (also mention if you are running on a cloud service)
*    Postgres and Postgis version
*    list of settings you changed in your Postgres configuration
*    Nominatim version (release version or, if you run from the git repo, the output of git rev-parse HEAD)

**Comment by mtmail** [comment]
One thought: I've used cloud (AWS?) servers that didn't have any swap enabled.

**Comment by chrissfoot** [comment]
Sorry for the lack of specs!

It's running on a Debian 8.8 local vm which I have complete control of.

Postgres 9.4 
Postgis 2.1

Postgres settings (i've tried without any custom settings at all too):
```
default_statistics_target = 50 # pgtune wizard 2018-01-05
maintenance_work_mem = 960MB # pgtune wizard 2018-01-05
constraint_exclusion = on # pgtune wizard 2018-01-05
checkpoint_completion_target = 0.9 # pgtune wizard 2018-01-05
effective_cache_size = 5GB # pgtune wizard 2018-01-05
work_mem = 50MB # pgtune wizard 2018-01-05
wal_buffers = 8MB # pgtune wizard 2018-01-05
checkpoint_segments = 16 # pgtune wizard 2018-01-05
shared_buffers = 2048MB
fsync = off
full_page_writes = off
synchronous_commit = off
```
I've tried Nominatim 3.0.0 and 3.0.1

I have 4gb of swap enabled but it doesn't appear to get used.

It's worth pointing out that a tiny import (Malta, just 4mb) fails with the same out of memory issue.

**Comment by lonvia** [comment]
I guess you are running Virtualbox and the flatnode file is located in a shared folder. A while ago I learned the hard way that this won't indeed work because the Virtualbox shared file system does not support memory-mapped files. I've run into this a while ago and couldn't find any good workaround. You must move the flatnode file to the locale virtual disk or use something like NFS. Problem is that it needs around 40GB memory now and there are rarely ready made boxes with that much disk space.

If you import just up to the size of Europe, there is not much gain in terms of disk space anyway, so I tend to recommend not to use flatnode files when running in a VM. But we really should be doing something about the issue, at the very least put a big warning on our Vagrant instructions that --flatnode might not work.

I'm also wondering about using zfs. Flatnode files for Europe or less do compress really nicely.

**Comment by chrissfoot** [comment]
Unfortunately not. This is a VMware VM on a vsphere server with its own 1tb drive. No sharing at all.

**Comment by lonvia** [comment]
Too bad. I suspect the underlying problem is the same though, something in VMware does not support remap(). Unfortunately, I have zero experience with VMware, so can't be of much help. I suggest you find out what kind of storage device your file system is on and try to google from there. I can also try and come up with a small test program to confirm that the missing remap() support is the issue, so that we can exclude any other out-of-memory conditions.

**Comment by chrissfoot** [comment]
I've had a chat to the IT Director who runs the vm host and this vm is using storage physically mounted in a nas box so the i/o for it actually goes over the network. We have now built another vm which uses a local hard disk and it does import with flatnodes enabled and is unsurprisingly, considerably quicker! Unfortunately there isn't enough local storage for the whole Europe import (the host only has a 250gb disk in it) so I think we'll be buying some new hardware! 

So while it does look like it's an issue with the remap() support I don't think it's caused by vmware itself, rather the type of storage that vmware is using.

Thanks for your help

**Comment by lonvia** [comment]
Thanks for figuring that out. Network storage definitely isn't a good idea for the flatnode file, given that it is pretty IO heavy. Still, I think there is a use-case for wanting to test out an installation in a VM with remapping restrictions. So it would be nice to make that work. I'll leave the issue open for now and play around with it a bit at some point. (PS.: if you get new hardware, get SSD storage.)
