### ISSUE TITLE
UK postcodes not found

### ISSUE THREAD

**Issue by stevewolfe555** [openstreetmap/Nominatim#890]
Hello,

When searching my local open maps install it finds some postcodes but not all. 

However, when I search on your version i can find them all.

I have been running the updater for the UK OSM which seems to work.

Is there a way to check the postcode database / update it?

**Comment by mtmail** [comment]
Can you list which version of Nominatim you installed, when the first full import was and which source data (one country or the whole world?). A couple of postcodes, which are not found will also help.

Nominatim 3.1 changed postcode handling significantly https://github.com/openstreetmap/Nominatim/releases/tag/v3.1.0 though that shouldn't impact queries consisting only of UK(*) postcodes as much.

As first step you could try to find those postcodes in the `gb_postcode` table.

*) Actually GB because Northern Ireland postcodes are not part of `data/gb_postcode_table.sql` https://github.com/openstreetmap/Nominatim/tree/v3.1.0/data

**Comment by stevewolfe555** [comment]
for example http://interweb360.ddns.net/nominatim/search.php?q=en10+6ad&polygon_geojson=1&viewbox=

https://www.openstreetmap.org/search?query=en10%206ad#map=13/51.7439/-0.0175

**Comment by lonvia** [comment]
Searching for UK postcodes from the external postcode table (i.e. for UK postcodes that are not in OSM) only works since Nominatim 3.1.0 (See #782). You need to do a complete reimport of your database with the new version and not forget to download the file with the additional postcodes before doing so.

**Comment by stevewolfe555** [comment]
@lonvia Thank you, is there a guide on how to update?

**Comment by lonvia** [comment]
As I said, you must install from scratch. See http://nominatim.org/release-docs/latest/admin/Installation/ .
