### ISSUE TITLE
Potential bad search result - Silicon Valley

### ISSUE THREAD

**Issue by resuni** [openstreetmap/Nominatim#893]
When searching Nominatim for "Silicon Valley", the first results are locations in Africa: https://nominatim.openstreetmap.org/search.php?q=Silicon+Valley&polygon_geojson=1&viewbox=

Top result is in Uganda: https://nominatim.openstreetmap.org/details.php?place_id=157648116

This may be the expected result, however if I attempt to narrow the search to "Silicon Valley, US" or "Silicon Valley, CA, US", no results are returned: https://nominatim.openstreetmap.org/search.php?q=Silicon+Valley%2C+CA%2C+US&polygon_geojson=1&viewbox=

The expected result would be to show a region centering around the area of Palo Alto: https://nominatim.openstreetmap.org/details.php?place_id=178952776

I understand that "Silicon Valley" is the nickname of a place with subjective boundaries, and I'm not sure what OSM does in cases like this, but I figured I'd open an issue to find out.

**Comment by SomeoneElseOSM** [comment]
To be honest, it doesn't sound like a bug in nominatim to me.  Whether or not a nickname for a region should be in OSM as a "place" is something best discussed with mappers on the ground in the area.

**Comment by mtmail** [comment]
I used to live there several years, if that helps. Silicon Valley is the name globally known in the IT sector since decades. Amazon.com book search lists 50.000 results https://www.amazon.com/gp/search/ref=sr_pg_4?rh=k%3Asilicon+valley%2Cn%3A283155

https://en.wikipedia.org/wiki/List_of_technology_centers has a couple of notability criteria near the top which this Silicon Valley passes. But I agree many - if not most others - on the page carrying "Silicon" in their name would need additional verification. Some seem to be more ambitions (press releases) than real uses. For example I know and used https://en.wikipedia.org/wiki/Silicon_Roundabout in conversations but in this case it's not known beyond the local London tech scene.

**Comment by lonvia** [comment]
As @SomeoneElseOSM has already noted: this is not a discussion for this issue tracker. It is a data issue and as such best discussed on the local mailing list. I recommend talk-us@ in this particular case.

**Comment by mtmail** [comment]
@resuni I added the place https://www.openstreetmap.org/changeset/55834648 after discussion on the talk-us-sfbay mailing list. https://nominatim.openstreetmap.org/search.php?q=silicon+valley
