### ISSUE TITLE
How long should xml parsing take?

### ISSUE THREAD

**Issue by stevewolfe555** [openstreetmap/Nominatim#896]
Hi does this look right, it seems to still be trying to parse the XML 2 days later.
Its not even stared indexing.
Was I meant to unzip the file first?
Thanks in advance this is my first time with the whole planet install.
![image](https://user-images.githubusercontent.com/6985460/35436797-bb818b50-0287-11e8-9e98-f3d9fd858928.png)

**Comment by mtmail** [comment]
Taking a full day isn't unusual in this step. What hardware to do run? Is the postgresql data directory network mounted instead of local SSD for example?

The full import can take 2-3 days even on newest hardware, e.g. 24cores, 128GB RAM, NVM discs

**Comment by stevewolfe555** [comment]
Hi I have it running on a 7200 1TB HDD.

16gb 8 core

**Comment by mtmail** [comment]
Disk IO will be the bottleneck here. With 7200rpm you're looking at a week for the full import, we even had user reports of two weeks.

I'm not entirely sure if 16GB RAM is enough for the full import. We recommend 32GB (http://nominatim.org/release-docs/latest/admin/Installation/#hardware) for  planet import. The risk is that postgresql starts swapping to disk which will again slow the whole process down because that's all random access.

**Comment by stevewolfe555** [comment]
I dont mind waiting for the time this is just a dev environment for now. Later on, we will look at a hosted solution. 
Ideally, we want to process about 1mill geocodes a month.

**Comment by mtmail** [comment]
Cool. Keep the machine running, the query-time performance will be fine (1m/month is less than 1 query per second). I'm closing this, but feel free to open a new issue should the import fail.
