### ISSUE TITLE
The continent Europe is the parent of only one country: Germany

### ISSUE THREAD

**Issue by siffash** [openstreetmap/Nominatim#904]
[https://nominatim.openstreetmap.org/details.php?place_id=125530](https://nominatim.openstreetmap.org/details.php?place_id=125530)
In the **Parent Of** section I expected to see the list of all European countries :)

**Comment by mtmail** [comment]
The highest level of places Nominatim supports is countries (admin_level=2, more or less anything that has an ISO country code). Anything covering multiple countries like continents, trade associations, military associations, constructs like United Kingdom, super-national administrations (the EU), even mountain ranges like the alps get assigned a to single country, usually at the center point. That's why the node Europe show an admin_level=15.

Country borders can sometimes be disputed already, assigning them to continents it gets even more complicated. For example Turkey (Istanbul) is in two continents. France has https://en.wikipedia.org/wiki/Overseas_territory_(France), there's a Spanish city in Africa https://en.wikipedia.org/wiki/Ceuta. We'd have to support, or even hardcode, many edge-cases for essentially "just" 7 continents.

**Comment by siffash** [comment]
Thank you @mtmail for your answer!
