### ISSUE TITLE
Nominatim API offline (particulary reverse geocoding)?

### ISSUE THREAD

**Issue by Jardeen** [openstreetmap/Nominatim#907]
Hey guys,

since 36h we detect some issues with Nominatim API:

The reverse geocoding API responds with an 503 or 429 error, but sometimes it works.
https://nominatim.openstreetmap.org/reverse?format=json&lat=50.0&lon=10.0

<img width="769" alt="reverse-503" src="https://user-images.githubusercontent.com/36235099/35924073-507be3c4-0c22-11e8-8a61-5e4100f9e7c6.png">

And the forward search responds mostly right but sometimes an 503 error.
https://nominatim.openstreetmap.org/search?format=json&q=berlin&countrycodes=de&zoom=4&addressdetails=1&limit=1&accept-language=en

Both tested with servers and different client browser located in Germany with different IP addresses, so this 429 error can not be because of reaching the limits.

Are there any technical issues at Nominatim API?

**Comment by lonvia** [comment]
We are aware of the issues and try to get the situation back to normal. The server is fighting with overload due to abusive clients who don't consider the amount of load they put on OSM's volunteer-operated infrastructure. Unfortunately, nobody bothers to read [terms of service](https://operations.osmfoundation.org/policies/nominatim/) these days or even bother to find out where that random library they downloaded from the internet gets its data.

If you are looking for better guarantees with respect to availability, I recommend looking into [commercial providers for the Nominatim API](https://wiki.openstreetmap.org/wiki/Nominatim#Alternatives_.2F_Third-party_providers).

**Comment by Jardeen** [comment]
Thanks so much for your reply. I will check the commercial providers.
