### ISSUE TITLE
addr:place objects not found

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/Nominatim#912]
Following a [recent thread on talk-it](https://lists.openstreetmap.org/pipermail/talk-it/2018-February/061988.html), it was noted that nominatim has problems locating objects which are tagged with addr:place and addr:housenumber.

For example: **https://www.openstreetmap.org/node/5107139653**
Currently tagged like this:

addr:city | Caprile
addr:housenumber | 14
addr:place | Frazione Uccelli
addr:postcode | 13864

None of the following searches returns this object:
`
"frazione uccelli 14, caprile"

"caprile, frazione uccelli 14"

"uccelli 14, caprile"
`

It might have to do with the fact that the addr:place has the "Frazione" prefix in its name (de~Ortsteil) while the place=hamlet object hasn't, but on the other hand the [documentation for addr:place](https://wiki.openstreetmap.org/wiki/Key:addr:place) states that it is not required to have an object with the same name in order to add this type of address: 

> Sometimes, addresses don't contain the name of any street. Some addresses are made with the scheme "<name of some territory>, <number of house>". It can be the name of a village, islands, territorial zone or any other object (sometimes, there is no existing object with that name).

**Comment by lonvia** [comment]
The wiki is wrong. Nominatim does require that an object with the exact same name exists. addr:place and addr:street are tags that are use for finding the point of reference for the house number. This is a fundamental concept of Nominatim and cannot be changed.

If you want to just describe an address part without any necessary relation to existing OSM objects use addr:city, addr:suburb, addr:municipality or similar. Add the locality twice if the name of the locality that should be shown diverges, i.e in above case add addr:place=Uccelli and addr:suburb=Frazione Uccelli.

**Comment by dieterdreist** [comment]
Thank you for taking the time to explain the issue. This means Nominatim requires always a place, and if you only know an address, you can enter the complete address into OSM but until an object with place=* and matching name is entered nearby, it will not be found in the nominatim search, right?

**Comment by lonvia** [comment]
The matter is a bit more complicated: the address might be found but it will be in no case displayed.

Nominatim does read all tags that start with 'addr:' and saves them. If you looking into the [details for your example above](https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=5107139653), you'll see all the address tags listed in the 'Address Tags' section. If this was a fully indexed object, then Nominatim would also put these names into the search index and you would be able to find it.  However when it comes to house numbers, a special optimisation comes into play: only the street (or place) the house number refers to is saved in the search index and search works backward from there. Naturally, this means that there must be an OSM object to index. That is where the requirement comes from that addr:street and addr:place refer to real objects.

As long as the addr:street or addr:place is missing, Nominatim sticks to its default treatment and attaches the house number to the closest road (currently: closest _named_ road, which really doesn't help and needs fixing). So you can find the house number only under the search terms that the attached road has (including any addr: tags there).

The display_name that is output for a search result is a different matter. It is always computed from the geographic address that Nominatim computes from boundary, so not even addr: tags help. You should still add the tags because it is useful information and one day even Nominatim gets around showing them.

For more explanation of geographic address vs. postal address, see [the postcode blogpost](http://www.openstreetmap.org/user/lonvia/diary/43143) and [this comment](https://github.com/komoot/photon/pull/303#issuecomment-360576105). The open issue for adding postal addresses is #148.

**Comment by polarbearing** [comment]
Hi @lonvia - we are using addr:place for the addresses of the [Stadtbahnbögen in Berlin](https://de.wikipedia.org/wiki/Stadtbahnb%C3%B6gen_%28Berlin%29), which are kind of a virtual street. 
Following this requirement here, I've added place=locality to the site relation. 
While the node object, [example](https://nominatim.openstreetmap.org/details?osmtype=N&osmid=2707660451), is considered by nominatim, the [relation](https://nominatim.openstreetmap.org/details?osmtype=R&osmid=3563707) gets a "Bad request - Details: Please select a place id".  As a side question, alt_name would work?

**Comment by mtmail** [comment]
Hi @polarbearing, 
Can you open a new issue with your questions? This issue got closed a while back and it's easy for us to loose overview which questions are unanswered.
thanks!
