### ISSUE TITLE
document where generic terms may be translated

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/Nominatim#962]
It seems that Nominatim is capable of translating generic search terms (at least it seems so from my experiments like https://www.openstreetmap.org/search?query=Piekarnia%2C%20Kraków ).

It is probably translated on Transifex or similar site but it seems to not be documented in https://github.com/openstreetmap/Nominatim/blob/master/CONTRIBUTING.md or README.

I am asking primarily because it seems that translation project for OSM tags would be useful and I want to start from reviewing existing ones (including what features would be considered useful in a new project) - see https://github.com/openstreetmap/iD/issues/2708 and https://github.com/ENT8R/tags2names/issues/1

Also, results for some generic terms are poor and I wanted to start checking what is causing issues from reviewing translations.

**Comment by mtmail** [comment]
On the first URL which term is translated? Maybe I don't see it in my browser set to english.

**Comment by matkoniecz** [comment]
"piekarnia" means bakery and found items include https://www.openstreetmap.org/node/1862001165 that is without "piekarnia" in name, but with shop=bakery.

So I suspect that Nominatim recognized somehow that shop=bakery means "bakery" and that Polish word for bakery is "piekarnia".

**Comment by mtmail** [comment]
Ah, ok. That's called Special Keywords in Nominatim search. Documented in the search API documentation https://wiki.openstreetmap.org/wiki/Nominatim#Special_Keywords

It seems the other github issues about translation project for OSM tags are still ongoing discussions without wider consent.

> Also, results for some generic terms are poor

Not necessarily caused by translations. https://www.openstreetmap.org/search?query=Piekarnia,Krakow does text matching on the name of bakeries. While https://www.openstreetmap.org/search?query=piekarnia+blisko+Krakow ('blisko' = Polish for 'near') triggers Nominatim to check the tags of places. So a user will need to use near/in/around and only a subset of POI related terms work.

**Comment by lonvia** [comment]
The other tag translations used by Nominatim can be found in the website repository in the [translations files](https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/en.yml#L378) under `geocoder/search_osm_nominatim/prefix`. Those are probably closer to the lists that ID has. Nominatim's special keywords are rather phrases particularly geared toward search and less of interest for a generic project.

Cleaning out the wiki documentation is something that is currently ongoing and the link to the special keywords wiki page will likely be moved to a more prominent place.

**Comment by lonvia** [comment]
Follow-up should probably go to the dev@ mailing list, as this issue might be of interest to a wider range of developers.
