### ISSUE TITLE
adding abbreviatons

### ISSUE THREAD

**Issue by nikkatalnikov** [openstreetmap/Nominatim#964]
Do you accept PRs for abbreviations addition?
The lists for Russian and Ukrainian here are not implemented and also should be extended
https://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations

**Comment by lonvia** [comment]
Please add them to the list in the wiki for later reference. At the moment, they are not really accepted into the software because two essential problems need to be solved:

* Abbreviations can only be updated on a complete database reimport, so just updating them in the repo here means that people cannot update the Nominatim software without a reimport. We need a mechanism where the current set of abbreviations is saved with the database, not with the software.
* Abbreviations tend to cause a lot of bad matches when they are shortened to one or two letter words.
