### ISSUE TITLE
Search for Anchorage, Alaska doesn't return Anchorage county

### ISSUE THREAD

**Issue by EdwardBetts** [openstreetmap/Nominatim#982]
https://nominatim.openstreetmap.org/search.php?q=Anchorage%2C+Alaska
Missing Anchorage country: https://www.openstreetmap.org/relation/2605259

Searching for Anchorage county, Alaska does find Anchorage country
https://nominatim.openstreetmap.org/search.php?q=Anchorage+county%2C+Alaska

**Comment by lonvia** [comment]
The culprit here was the (now deleted) `addr:postcode=Alaska` in [this node](https://www.openstreetmap.org/node/2797835281). It caused only results close to the node to be returned. The county does show up but only after selecting 'More results'. Hopefully this sorts itself out by tomorrow, then the postcode should also be removed again from Nominatim's database.

There is a more involved issue with Nominatim's search that needs to be solved to be more resilient against these kind of tagging errors. I've opened a more specific issue (#988) for that. Closing here.
