### ISSUE TITLE
the number of nominatim

### ISSUE THREAD

**Issue by cheeta2018** [openstreetmap/Nominatim#997]
I have a problem about the number of points，lines，areas and the total amount in the nominatim database.
Thank you very much!!!

**Comment by lonvia** [comment]
I'm sorry but there is absolutely no way to even start to guess what your issue might be.

Please read [the contribution guide](https://github.com/openstreetmap/Nominatim/blob/master/CONTRIBUTING.md) carefully. Then state what you are trying to do, what you did so far to reach your goals and what setup you were using for that, what you expected the outcome to be and what the actual outcome was.

If you have a question about the Nominatim installation rather than a bug report, please use the [geocoding mailinglist](https://lists.openstreetmap.org/listinfo/geocoding) instead of this issue tracker.
